/**
 * The harness module's UI copy: the zh and en fragments of the app dictionaries, mounted by
 * reference as their `harnessHistory` section. A new string is added here, to both fragments, and
 * nowhere else — `HarnessHistoryStrings` makes a key missing from `harnessHistoryEn` a type error.
 */
export const harnessHistoryZh = {
  title: "Harness 历史",
  pageDesc:
    "这台服务器通过热更新提交过的每个 harness 版本，最新在前，以及每次推送在模块树与接口上改了什么。",
  loading: "加载中…",
  empty: "还没有向这台服务器推送过 harness。",
  current: "当前",
  noProvenance: "（未记录来源）",
  pushedAt: "提交时间",
  bundles: "Bundle",
  table: "接口表",
  tableCounts: (nodes: number, interfaces: number, types: number) =>
    `${nodes} 个节点 · ${interfaces} 个接口 · ${types} 个类型`,
  noTable: "这次推送没有携带接口表。",
  noTableShort: "无表",
  changesSince: (previous: string) => `相对 ${previous} 的变化`,
  changesFirst: "变化（首个记录的表）",
  noChanges: "接口与树没有变化。",
  nodes: (n: number) => `节点（${n}）`,
  interfaces: (n: number) => `接口（${n}）`,
  typesSummary: (added: number, removed: number, changed: number) =>
    `数据类型：新增 ${added}，移除 ${removed}，变化 ${changed}`,
  change: { added: "新增", removed: "移除", changed: "变化" },
  rollback: "回滚到这个版本",
  rollbackConfirm: "把这个版本推回去并立即切换？",
  rollbackYes: "回滚",
  rollbackPushing: "推送中……到达后服务器会切换。",
  rollbackTimeout: "服务器没有及时报告切换；请查看历史。",
  notKept: "这个版本的产物没有保留，无法推回。",
  viewChanges: "变化",
  viewTree: "模块树",
  kind: { group: "组", module: "模块", component: "组件" },
  expand: "展开",
  collapse: "收起",
  extensionSlot: "+ 扩展模块",
  ownProvision: "自身",
  pickNode: "选一个节点，查看它需要和提供什么。",
  requires: "requires",
  provides: "provides",
  contributes: "contributes",
  children: "children",
  exports: "exports",
  methods: "方法",
  fields: "字段",
  slots: "槽位",
};

export type HarnessHistoryStrings = typeof harnessHistoryZh;

export const harnessHistoryEn: HarnessHistoryStrings = {
  title: "Harness history",
  pageDesc:
    "Every harness version this server committed through a hot update, newest first, and what each push changed in the module tree and its interfaces.",
  loading: "Loading…",
  empty: "No harness has been pushed to this server yet.",
  current: "current",
  noProvenance: "(no provenance recorded)",
  pushedAt: "Committed",
  bundles: "Bundles",
  table: "Interface table",
  tableCounts: (nodes: number, interfaces: number, types: number) =>
    `${nodes} nodes · ${interfaces} interfaces · ${types} types`,
  noTable: "This push carried no interface table.",
  noTableShort: "no table",
  changesSince: (previous: string) => `Changes since ${previous}`,
  changesFirst: "Changes (first recorded table)",
  noChanges: "No interface or tree changes.",
  nodes: (n: number) => `Nodes (${n})`,
  interfaces: (n: number) => `Interfaces (${n})`,
  typesSummary: (added: number, removed: number, changed: number) =>
    `Data types: ${added} added, ${removed} removed, ${changed} changed`,
  change: { added: "added", removed: "removed", changed: "changed" },
  rollback: "Roll back to this version",
  rollbackConfirm: "Push this version back and swap now?",
  rollbackYes: "Roll back",
  rollbackPushing: "Pushing… the server swaps when it lands.",
  rollbackTimeout: "The server did not report the swap in time; check the history.",
  notKept: "Artifacts of this version were not kept; it cannot be pushed back.",
  viewChanges: "Changes",
  viewTree: "Module tree",
  kind: { group: "group", module: "module", component: "component" },
  expand: "Expand",
  collapse: "Collapse",
  extensionSlot: "+ extension modules",
  ownProvision: "own",
  pickNode: "Pick a node to see what it requires and provides.",
  requires: "requires",
  provides: "provides",
  contributes: "contributes",
  children: "children",
  exports: "exports",
  methods: "methods",
  fields: "fields",
  slots: "slots",
};
