// Generated by scripts/gen-renderers.ts from src/module.json; do not edit.
// Regenerate with `node scripts/gen-renderers.ts` (test/renderers.test.ts checks it is current).

/** The page renderers this build carries: a page naming another `builtin` shows it is unavailable. */
export const PAGE_RENDERER_NAMES = [
  "ChatPage",
  "AgentsPage",
  "AgentSettingsPage",
  "PluginsPage",
  "ModelsPage",
  "PluginDetailPage",
  "MachinesPage",
  "MachinePortsPage",
  "UsagePage",
  "BenchmarkPage",
  "BenchmarkDetailPage",
  "DashboardPage",
  "OrgProposalsPage",
] as const;
export type PageRendererName = (typeof PAGE_RENDERER_NAMES)[number];

/** The session surface renderers this build carries. */
export const SURFACE_RENDERER_NAMES = ["TerminalSurface"] as const;
export type SurfaceRendererName = (typeof SURFACE_RENDERER_NAMES)[number];

/** The company-mode nav rows of contributed pages, in row order (features/company/company-nav.ts). */
export const ORG_PAGE_RENDERERS = {
  roadmaps: {
    label: "roadmaps",
    segment: "roadmaps",
    kind: "iframe",
  },
  OrgProposalsPage: {
    label: "proposals",
    segment: "proposals",
    kind: "builtin",
  },
} as const;
