/**
 * The renderer registry (src/module.json `renderers`, generated by scripts/gen-renderers.ts):
 * the generated files are the manifest's current output, every renderer a page or a shipped
 * plugin names is declared, and the generator refuses a manifest that names a renderer or a
 * module it does not have.
 */
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import {
  OUTPUTS,
  generateFromDisk,
  generateRegistry,
  type WebManifest,
} from "../scripts/gen-renderers";
import {
  ORG_PAGE_RENDERERS,
  PAGE_RENDERER_NAMES,
  SURFACE_RENDERER_NAMES,
} from "../src/lib/renderers.gen";
import { PAGES } from "../src/lib/pages";

describe("the generated registry", () => {
  it("is current with src/module.json (run `node scripts/gen-renderers.ts` if not)", async () => {
    const out = await generateFromDisk();
    expect(readFileSync(OUTPUTS.data, "utf8")).toBe(out.data);
    expect(readFileSync(OUTPUTS.components, "utf8")).toBe(out.components);
  });

  it("declares every builtin renderer a local page names", () => {
    const names: readonly string[] = PAGE_RENDERER_NAMES;
    for (const page of PAGES) {
      if ("builtin" in page.renderer) expect(names).toContain(page.renderer.builtin);
    }
  });

  it("declares the renderers the shipped plugins name", () => {
    // company-proposals contributes an org page drawn by OrgProposalsPage; claude-code a
    // surface drawn by TerminalSurface.
    expect(PAGE_RENDERER_NAMES).toContain("OrgProposalsPage");
    expect(SURFACE_RENDERER_NAMES).toContain("TerminalSurface");
    expect(ORG_PAGE_RENDERERS.OrgProposalsPage.kind).toBe("builtin");
  });
});

describe("generateRegistry", () => {
  const base = (): WebManifest => ({
    contributes: { "web.pages": [{ key: "a", renderer: { builtin: "APage" } }] },
    renderers: {
      pages: [{ name: "APage", module: "a" }],
      surfaces: [{ name: "ASurface", module: "a", export: "Surface" }],
      orgNav: [{ key: "APage", kind: "builtin", label: "a", segment: "a" }],
    },
  });
  const exists = (module: string) => module === "a";

  it("imports each renderer through its module's entry, renamed when the export differs", () => {
    const out = generateRegistry(base(), exists);
    expect(out.components).toContain('import { APage, Surface as ASurface } from "./features/a";');
    expect(out.data).not.toContain("import ");
  });

  it("refuses a page naming an undeclared renderer", () => {
    const m = base();
    m.contributes["web.pages"].push({ key: "b", renderer: { builtin: "BPage" } });
    expect(() => generateRegistry(m, exists)).toThrow(/page "b" names renderer "BPage"/);
  });

  it("refuses a renderer in a module without an entry", () => {
    const m = base();
    m.renderers.pages.push({ name: "BPage", module: "b" });
    expect(() => generateRegistry(m, exists)).toThrow(/module "b"/);
  });

  it("refuses a duplicate name and a builtin nav row naming no page renderer", () => {
    const dup = base();
    dup.renderers.pages.push({ name: "APage", module: "a" });
    expect(() => generateRegistry(dup, exists)).toThrow(/declared twice/);
    const row = base();
    row.renderers.orgNav.push({ key: "Missing", kind: "builtin", label: "m", segment: "m" });
    expect(() => generateRegistry(row, exists)).toThrow(/org nav row "Missing"/);
  });
});
