/**
 * The Web App's module manifest: which feature directories are modules, and what each may
 * import from the rest of the app. vitest.config.ts derives one test project per entry, and
 * module-boundaries.test.ts enforces the rest, so the two cannot drift apart.
 *
 * A module is `src/features/<name>/` with:
 * - `index.ts`, its public entry — the only file outside code may import;
 * - `strings.ts`, its dictionary fragments `<section>Zh` and `<section>En` — imported only by the
 *   app dictionaries, which mount them as their `<section>` section (`section` defaults to the
 *   module's name; `null` is a module with no copy of its own, and no `strings.ts`);
 * - `test/`, its unit tests — run alone with `vitest run --project <name>`; they may also use the
 *   app's shared test helpers (`../test/…`), declared like any other dependency;
 * - `dependsOn`, the files outside the directory its own sources and tests may import, as
 *   paths relative to `src/` without extension. A path ending in `/` admits the whole
 *   directory. Another module is named by its entry (`features/<name>/index`).
 */
export interface WebModule {
  name: string;
  /** The app dictionaries' section this module's `strings.ts` fills; defaults to `name`. */
  section?: string | null;
  dependsOn: readonly string[];
}

export const WEB_MODULES: readonly WebModule[] = [
  {
    name: "terminal",
    dependsOn: [
      // The locale runtime (`S`) and the shared UI primitives.
      "lib/strings",
      "components/ui/",
      "lib/icon-scale",
      // Pointer and viewport hooks the touch key bar and the /terminal page size themselves by.
      "lib/use-coarse-pointer",
      "lib/use-visual-viewport-height",
      // The API client the shell list fetches with.
      "api/client",
      // Theme and sign-in state the view reads.
      "state/theme",
      "state/auth",
      // Where the server is, and which machine a shell runs on.
      "lib/server-context",
      "lib/terminal-machines",
      // The dock's visibility store: the view pool keeps a shell mounted while its dock tab is
      // hidden.
      "features/dock/index",
    ],
  },
  // The modules below declare what they imported when they became modules; a new dependency
  // is added here on purpose, not picked up.
  {
    name: "admin",
    dependsOn: [
      "../test/fragment-shape",
      "api/client",
      "api/endpoints",
      "components/ui/",
      "lib/api-error",
      "lib/format",
      "lib/semantic-id",
      "lib/strings",
      "state/auth",
    ],
  },
  {
    name: "agents",
    section: "agent",
    dependsOn: [
      "../test/fragment-shape",
      "api/client",
      "api/endpoints",
      "components/ui/",
      "features/ai-create/index",
      "features/chat/index",
      "features/schedules/index",
      "features/semantic-id/index",
      "features/skills/index",
      "lib/api-error",
      "lib/benchmark-merge",
      "lib/bulk-update",
      "lib/format",
      "lib/frontmatter",
      "lib/icon-scale",
      "lib/semantic-id",
      "lib/stat-icons",
      "lib/strings",
      "lib/strings-en",
      "lib/todo-dismissals",
      "lib/tone",
      "lib/use-document-title",
      "lib/use-update-badges",
      "state/auth",
      "state/locale",
      "state/project",
      "state/sessions",
    ],
  },
  {
    name: "ai-create",
    section: "aiCreate",
    dependsOn: [
      "../test/fragment-shape",
      "components/ui/",
      "features/chat/index",
      "lib/strings",
      "lib/strings-en",
      "lib/tone",
      "state/auth",
      "state/project",
    ],
  },
  {
    name: "benchmark",
    dependsOn: [
      "../test/fragment-shape",
      "api/client",
      "api/endpoints",
      "components/ui/",
      "features/ai-create/index",
      "features/chat/index",
      "features/semantic-id/index",
      "features/usage/index",
      "lib/api-error",
      "lib/benchmark-merge",
      "lib/category-colors",
      "lib/file-path",
      "lib/file-tree",
      "lib/format",
      "lib/icon-scale",
      "lib/stat-icons",
      "lib/strings",
      "lib/tone",
      "lib/use-document-title",
      "lib/workspace-machines",
      "lib/workspace-tree",
      "state/locale",
      "state/project",
      "state/sessions",
      "state/theme",
    ],
  },
  {
    name: "browser",
    dependsOn: [
      "../test/fragment-shape",
      "api/endpoints",
      "components/ui/",
      "features/dock/index",
      "lib/api-error",
      "lib/icon-scale",
      "lib/strings",
      "lib/workflow-theme",
      "state/theme",
    ],
  },
  {
    name: "chat",
    dependsOn: [
      "${rel}",
      "../test/fragment-shape",
      "api/client",
      "api/endpoints",
      "api/socket",
      "api/sse",
      "components/ui/",
      "features/ai-create/index",
      "features/browser/index",
      "features/company/index",
      "features/dock/index",
      "features/messaging/index",
      "features/models/index",
      "features/ports/index",
      "features/proposals/index",
      "features/schedules/index",
      "features/settings/index",
      "features/skills/index",
      "features/terminal/index",
      "features/traces/index",
      "features/workflows/index",
      "lib/account-menu",
      "lib/api-error",
      "lib/attachments",
      "lib/category-colors",
      "lib/context",
      "lib/context-menu",
      "lib/file-drop",
      "lib/file-path",
      "lib/format",
      "lib/frontmatter",
      "lib/icon-scale",
      "lib/machine-cache",
      "lib/markdown-plugins",
      "lib/omni/compaction-summary",
      "lib/omni/memory-changes",
      "lib/omni/stream-controller",
      "lib/omni/stream-model",
      "lib/omni/task-stats",
      "lib/permission-level",
      "lib/random-id",
      "lib/reply-link",
      "lib/selection-menu",
      "lib/session-activity",
      "lib/session-grouping",
      "lib/session-machines",
      "lib/session-seen",
      "lib/stat-icons",
      "lib/strings",
      "lib/strings-en",
      "lib/strip-ansi",
      "lib/terminal-machines",
      "lib/tone",
      "lib/tool-alias",
      "lib/update-flow",
      "lib/upload-limits",
      "lib/use-document-title",
      "lib/use-update-flow",
      "lib/use-version-info",
      "lib/workspace-machines",
      "lib/workspace-tree",
      "state/auth",
      "state/company",
      "state/contributions",
      "state/locale",
      "state/project",
      "state/sessions",
      "state/theme",
    ],
  },
  {
    name: "company",
    dependsOn: [
      "../test/fragment-shape",
      "api/client",
      "api/endpoints",
      "components/ui/",
      "features/chat/index",
      "features/dock/index",
      "features/messaging/index",
      "features/models/index",
      "features/proposals/index",
      "features/semantic-id/index",
      "features/skills/index",
      "features/traces/index",
      "features/usage/index",
      "lib/api-error",
      "lib/avatar-image",
      "lib/category-colors",
      "lib/file-tree",
      "lib/format",
      "lib/icon-scale",
      "lib/org-machines",
      "lib/renderers.gen",
      "lib/semantic-id",
      "lib/session-activity",
      "lib/session-grouping",
      "lib/stat-icons",
      "lib/strings",
      "lib/strings-en",
      "lib/tone",
      "lib/use-document-title",
      "lib/work-mode",
      "lib/workspace-machines",
      "state/auth",
      "state/company",
      "state/locale",
      "state/project",
      "state/sessions",
      "state/theme",
    ],
  },
  {
    name: "dashboard",
    dependsOn: [
      "../test/fragment-shape",
      "api/endpoints",
      "components/ui/",
      "features/chat/index",
      "lib/api-error",
      "lib/icon-scale",
      "lib/session-activity",
      "lib/session-grouping",
      "lib/session-machines",
      "lib/session-seen",
      "lib/strings",
      "lib/tone",
      "lib/use-document-title",
      "lib/workspace-machines",
      "state/project",
    ],
  },
  {
    name: "dock",
    dependsOn: [
      "../test/fragment-shape",
      "components/ui/",
      "features/browser/index",
      "features/chat/index",
      "features/terminal/index",
      "lib/context-menu",
      "lib/icon-scale",
      "lib/sheet-physics",
      "lib/spring",
      "lib/strings",
      "lib/terminal-machines",
      "lib/tone",
      "lib/use-coarse-pointer",
    ],
  },
  {
    name: "harness",
    section: "harnessHistory",
    dependsOn: [
      "../test/fragment-shape",
      "api/endpoints",
      "components/ui/",
      "lib/format",
      "lib/strings",
      "lib/tone",
    ],
  },
  {
    name: "machines",
    dependsOn: [
      "../test/fragment-shape",
      "api/endpoints",
      "components/ui/",
      "lib/api-error",
      "lib/format",
      "lib/icon-scale",
      "lib/strings",
      "lib/tone",
      "lib/use-document-title",
      "state/locale",
      "state/project",
    ],
  },
  {
    name: "messaging",
    dependsOn: [
      "../test/fragment-shape",
      "api/client",
      "api/endpoints",
      "components/ui/",
      "lib/api-error",
      "lib/format",
      "lib/strings",
      "lib/strings-en",
      "lib/tone",
    ],
  },
  {
    name: "models",
    dependsOn: [
      "../test/fragment-shape",
      "api/client",
      "api/endpoints",
      "components/ui/",
      "features/ai-create/index",
      "features/chat/index",
      "lib/api-error",
      "lib/bulk-update",
      "lib/format",
      "lib/icon-scale",
      "lib/session-order",
      "lib/strings",
      "lib/strings-en",
      "lib/todo-badges",
      "lib/todo-dismissals",
      "lib/tone",
      "lib/use-document-title",
      "lib/use-project-todos",
      "lib/use-update-badges",
      "state/auth",
      "state/project",
      "state/theme",
    ],
  },
  {
    name: "palette",
    section: "commandPalette",
    dependsOn: [
      "../test/fragment-shape",
      "api/endpoints",
      "components/ui/",
      "features/harness/index",
      "lib/api-error",
      "lib/command-palette",
      "lib/strings",
      "state/auth",
      "state/locale",
    ],
  },
  {
    name: "plugins",
    dependsOn: [
      "../test/fragment-shape",
      "api/client",
      "api/endpoints",
      "components/ui/",
      "features/chat/index",
      "features/machines/index",
      "features/settings/index",
      "features/skills/index",
      "lib/api-error",
      "lib/bulk-update",
      "lib/file-tree",
      "lib/format",
      "lib/icon-scale",
      "lib/markdown-plugins",
      "lib/strings",
      "lib/todo-dismissals",
      "lib/tone",
      "lib/use-document-title",
      "lib/use-update-badges",
      "lib/workspace-tree",
      "state/auth",
      "state/contributions",
      "state/locale",
      "state/project",
      "state/sessions",
    ],
  },
  {
    name: "ports",
    dependsOn: [
      "../test/fragment-shape",
      "api/endpoints",
      "components/ui/",
      "features/browser/index",
      "features/dock/index",
      "lib/api-error",
      "lib/icon-scale",
      "lib/strings",
      "lib/tone",
      "lib/use-document-title",
      "state/auth",
      "state/locale",
      "state/project",
    ],
  },
  {
    name: "proposals",
    section: null,
    dependsOn: [
      "api/endpoints",
      "components/ui/",
      "features/chat/index",
      "features/company/index",
      "features/dock/index",
      "lib/api-error",
      "lib/format",
      "lib/icon-scale",
      "lib/strings",
      "lib/strings-en",
      "lib/tone",
      "lib/use-document-title",
      "state/auth",
      "state/company",
      "state/locale",
    ],
  },
  {
    name: "schedules",
    section: "schedule",
    dependsOn: [
      "../test/fragment-shape",
      "api/endpoints",
      "components/ui/",
      "features/ai-create/index",
      "features/chat/index",
      "features/models/index",
      "lib/api-error",
      "lib/format",
      "lib/icon-scale",
      "lib/strings",
      "lib/strings-en",
      "lib/tone",
      "state/locale",
      "state/project",
    ],
  },
  {
    name: "semantic-id",
    section: "semanticId",
    dependsOn: [
      "../test/fragment-shape",
      "api/endpoints",
      "components/ui/",
      "lib/api-error",
      "lib/icon-scale",
      "lib/strings",
      "lib/strings-en",
      "lib/tone",
    ],
  },
  {
    name: "settings",
    dependsOn: [
      "../test/fragment-shape",
      "api/client",
      "api/endpoints",
      "components/account/change-password-dialog",
      "components/ui/",
      "features/admin/index",
      "features/chat/index",
      "features/dock/index",
      "features/machines/index",
      "lib/account-menu",
      "lib/api-error",
      "lib/avatar-image",
      "lib/icon-scale",
      "lib/notification-pref",
      "lib/profile-form",
      "lib/settings-sections",
      "lib/strings",
      "lib/tone",
      "state/auth",
      "state/company",
      "state/locale",
      "state/project",
      "state/sessions",
      "state/theme",
    ],
  },
  {
    name: "skills",
    dependsOn: [
      "../test/fragment-shape",
      "components/ui/",
      "features/chat/index",
      "lib/icon-scale",
      "lib/strings",
      "state/locale",
    ],
  },
  {
    name: "traces",
    dependsOn: [
      "../test/fragment-shape",
      "api/endpoints",
      "components/ui/",
      "lib/api-error",
      "lib/context",
      "lib/format",
      "lib/icon-scale",
      "lib/markdown-plugins",
      "lib/stat-icons",
      "lib/strings",
      "lib/strings-en",
      "lib/tone",
      "state/theme",
    ],
  },
  {
    name: "usage",
    dependsOn: [
      "../test/fragment-shape",
      "api/endpoints",
      "components/ui/",
      "lib/api-error",
      "lib/category-colors",
      "lib/format",
      "lib/strings",
      "lib/strings-en",
      "lib/todo-dismissals",
      "lib/token-colors",
      "lib/tone",
      "lib/use-document-title",
      "lib/use-project-todos",
      "lib/use-update-badges",
      "state/project",
      "state/theme",
    ],
  },
  {
    name: "workflows",
    dependsOn: [
      "../test/fragment-shape",
      "api/endpoints",
      "api/sse",
      "components/ui/",
      "features/chat/index",
      "features/palette/index",
      "lib/command-palette",
      "lib/format",
      "lib/strings",
      "lib/tone",
      "lib/workflow-tabs",
      "lib/workflow-theme",
      "state/locale",
      "state/project",
      "state/theme",
    ],
  },
];
