// Generated by scripts/gen-renderers.ts from src/module.json; do not edit.
// Regenerate with `node scripts/gen-renderers.ts` (test/renderers.test.ts checks it is current).
import type { ComponentType } from "react";
import type { SurfaceRendererProps } from "./state/contributions";
import type { PageRendererName, SurfaceRendererName } from "./lib/renderers.gen";
import { AgentsPage, AgentSettingsPage } from "./features/agents";
import { BenchmarkPage, BenchmarkDetailPage } from "./features/benchmark";
import { ChatRoute as ChatPage, TerminalSurface } from "./features/chat";
import { DashboardPage } from "./features/dashboard";
import { MachinesPage } from "./features/machines";
import { ModelsPage } from "./features/models";
import { PluginsPage, PluginDetailPage } from "./features/plugins";
import { MachinePortsPage } from "./features/ports";
import { OrgProposalsPage } from "./features/proposals";
import { UsagePage } from "./features/usage";

/** Each page renderer the manifest declares, by name. */
export const PAGE_RENDERERS: Record<PageRendererName, ComponentType> = {
  ChatPage,
  AgentsPage,
  AgentSettingsPage,
  PluginsPage,
  ModelsPage,
  PluginDetailPage,
  MachinesPage,
  MachinePortsPage,
  UsagePage,
  BenchmarkPage,
  BenchmarkDetailPage,
  DashboardPage,
  OrgProposalsPage,
};

/** Each session surface renderer the manifest declares, by name. */
export const SURFACE_RENDERERS: Record<SurfaceRendererName, ComponentType<SurfaceRendererProps>> = {
  TerminalSurface,
};
