/**
 * The company module's UI copy: the zh and en fragments of the app dictionaries, mounted by
 * reference as their `company` section. A new string is added here, to both fragments, and
 * nowhere else — `CompanyStrings` makes a key missing from `companyEn` a type error.
 */
export const companyZh = {
  /** The mode switch (top-left of the sidebar, above the Project switcher) and its two options. */
  workMode: "工作模式",
  modeDev: "开发",
  modeCompany: "公司",
  switchToCompany: "切换到公司模式",
  switchToDev: "切换到开发模式",
  /**
   * Company mode is a beta, said in three shapes: the mini tag at the top-right of 「公司」 in
   * the work-mode switch (and the suffix the collapsed rail's tooltip carries in its place),
   * the tag's own tooltip, and the one sentence shown both under the admin's master switch
   * and as the notice a person gets the first time they enter the mode.
   */
  beta: "内测版",
  betaTitle: "公司模式是内测功能，可能有不稳定的现象",
  betaNotice: "内测功能：可能有不稳定的现象，遇到问题请反馈。",
  /** The organization switcher that replaces the Project switcher in company mode. */
  switcher: "组织",
  noOrganizations: "还没有组织",
  createOrg: "新建组织",
  orgSettings: "组织设置",
  orgInvalid: "配置无效",
  orgPaused: "已暂停",
  /** The switcher's check mark beside the open organization (sr text). */
  switcherCurrent: "当前组织",
  /** `<project> / <org>` in the switcher: the Project half of the label. */
  inProject: (project: string, org: string): string => `${project} / ${org}`,
  /** The empty landing of `/org` when the user has no organization anywhere. */
  landingTitle: "公司模式",
  landingBody:
    "组织是一群员工 Agent 按汇报线协作：一位 CEO、它招募的员工、共享的看板与频道，以及驱动它们的日程。新建一个组织，先和 CEO 谈谈使命。",
  /** The page a stale deep link lands on: the organization it names is gone. */
  orgGoneTitle: "组织不存在",
  orgGoneBody: "它可能已被删除，或者你不再能访问它所属的 Project。",
  backToOrgs: "回到组织列表",
  /** Create dialog. */
  createTitle: "新建组织",
  orgId: "组织 id",
  orgIdHint: "2~64 位：小写字母开头，仅小写字母、数字与下划线；也是目录名，创建后不可修改",
  displayName: "显示名",
  displayNameHint: "留空则使用组织 id",
  mission: "使命",
  missionHint: "一句话说明这个组织存在的目的；CEO 的初始化会话从它开始",
  missionPlaceholder: "例如：为 PenguinHarness 维护文档站，并每周发布一期更新摘要",
  /** The three examples under the mission field (org-examples.ts holds their order). */
  missionExampleHint: "点一下填入使命",
  missionExamples: {
    research: {
      name: "科研论文公司",
      mission:
        "新建一个公司帮我做科研，产出可以投稿顶级会议的学术论文。实验按 autoresearch 的方式跑：先固定评测脚本与指标，只改一个文件，每次实验限定时长，结果逐行记入日志，只保留有提升的改动。开始任何实验循环之前，研究员先在群里向我申请资源——机器与 GPU/CPU、并发数、总时长、磁盘与数据、付费 API——批准后在额度内自主运行，要超出就再申请。论文由作者与审稿人两类员工对抗评审：审稿人复现结果、查基线与消融、找测试集泄漏与指标作弊，给出评分与必改项；作者逐条修改或反驳，直到审稿人接受。",
    },
    agentTuning: {
      name: "Agent 优化公司",
      mission: "新建一个公司帮我优化产品 Agent，提高 Agent 在实际业务中的准确度和产品体验",
    },
    cloudReseller: {
      name: "云服务转售站",
      mission:
        "新建一个公司帮我运营一个类似云服务的网站，收集市面上所有的低价服务，并且加价以后打包出售，目的是帮我赚钱，并且要提高站点的 SEO 和曝光程度",
    },
    mirror: {
      name: "员工数字分身公司",
      mission:
        "新建一个公司，作为我们现实公司的镜像：我会把现实公司的组织图告诉 CEO，CEO 为每位现实员工创建一个数字分身；每个分身的工位会话绑定到那位同事的飞书机器人。分身默认只被动接收自己同事的消息，能自己解决的就直接回答，解决不了的转给相关同事的分身、再由对方分身转给真人。CEO 不主动招募、不排日程、不开工单，公司只做传话和自主解决问题。",
    },
  },
  createdOpeningCeo: "组织已创建，正在打开 CEO 的工位会话",
  /** Create and settings dialogs: the model and the shared workspace, both optional. */
  modelField: "模型",
  modelInfo:
    "工位会话与工单会话默认使用的模型；员工在组织图里另有指定时以员工的为准。改动从下一次工作轮起生效。",
  modelHint: "留空则使用 Project 的默认模型",
  /** The picker offers models only, so the way back to the Project default is its own control. */
  modelClear: "改回 Project 默认",
  /** The stored model is no longer in the Project's model list. */
  modelStale: "这个模型已不在 Project 的模型列表里",
  modelProjectDefault: "Project 默认",
  modelProjectDefaultNamed: (name: string): string => `Project 默认（${name}）`,
  modelsLoadFailed: "模型列表读取失败；仍可按 Project 默认模型创建",
  machineCompanyModeOff:
    "那台机器没有开启公司模式。请先在那台机器的设置里开启，再在它上面创建组织。",
  workspaceField: "公司工作区",
  workspaceInfo:
    "员工共同工作的目录：每位员工的工作区是它的一个子目录（或整个目录），工位会话与工单会话都在其中运行。它可以在 Project 已连接的某台机器上：组织随之在那台机器上运行——Agent 与会话都在那里——但仍属于当前 Project，这里保留它的文件副本。创建之后不能迁移。",
  workspaceHint:
    "留空则使用组织自己的 workspace/ 目录；指定时必须是已存在的目录，可在本机或已连接的机器上",
  workspaceEmpty: "组织自己的 workspace/ 目录",
  workspaceMenuHint: "选一个已存在的目录作为公司工作区",
  workspaceClear: "改回组织自己的目录",
  /** CEO budget field (create dialog): the CEO's ceiling is the company's, since everyone reports to it. */
  ceoBudget: "CEO 预算",
  ceoBudgetHint: "每月上限；CEO 的预算就是整家公司的预算",
  /** The create dialog's draft (org-draft.ts): restored on reopen, dropped on create or on demand. */
  draftRestored: "已恢复上次未提交的草稿",
  clearDraft: "清空草稿",
  creating: "创建中…",
  /** Settings dialog (the switcher's entry). */
  settingsTitle: "组织设置",
  timezone: "时区",
  timezoneHint: "IANA 时区名，如 Asia/Shanghai；预算周期（自然月）与频道日志按它划分",
  language: "工作语言",
  languageInfo:
    "组织的工作语言：手册、员工简报、CEO 初始化会话与各工位的输出都用这个语言；创建时按使命的语言自动判断。",
  languages: {
    zh: "中文",
    en: "English",
  },
  approvalMode: "审批模式",
  approvalModeInfo:
    "工位会话与工单会话的工具审批口径。无人值守的运行不会停下来等人拍板，所以这里没有「总是询问」。",
  approvalModes: {
    "allow-all": "全部放行",
    "read-only": "只读",
    "deny-all": "全部拒绝",
  } as Record<string, string>,
  status: "状态",
  statusActive: "运行中",
  statusPaused: "已暂停",
  pause: "暂停组织",
  resume: "恢复组织",
  deleteOrg: "删除组织",
  deleteOrgDesc: "把组织移入 Project 的回收目录。员工保留为 Agent，对话也保留。",
  deleteOrgConfirm:
    "组织会从公司模式里消失。组织的文件移入 Project 的回收目录（organizations/.trash），可以手工移回来恢复。员工仍是 Project 的 Agent；工位与工单的对话会保留，但组织不在了，就没有页面再列出它们。要再次使用这个 id，需先删除旧 CEO 的 Agent。只是想让组织停下来而不丢任何东西，请改用暂停。",
  deleteOrgTypeId: (orgId: string) => `输入 ${orgId} 以确认`,
  deleted: (orgId: string) => `组织 ${orgId} 已删除`,
  pauseInfo:
    "暂停后所有自动触发停止——日程不再到点、@ 不再送达员工；你仍可以打开任意工位会话直接对话。组织只会被暂停，不会被删除：它的对话、员工与工单始终可以回去看。",
  settingsLoadFailed: "组织设置读取失败",
  /** Employee state dot, and the CEO mark. */
  employeeStates: {
    running: "运行中",
    idle: "在岗",
    paused: "预算暂停",
  } as Record<string, string>,
  ceo: "CEO",
  reportsTo: (name: string): string => `汇报给 ${name}`,
  openDesk: "打开工位会话",
  openingDesk: "正在打开工位会话…",
  /** Principals as the chat and tickets name them. */
  principalSystem: "系统",
  principalAll: "所有人",
  /** Spend against a budget, and the unbounded case. */
  spendOfBudget: (spend: string, budget: string): string => `${spend} / ${budget}`,
  noBudget: "不限",
  /**
   * A budget is a monthly cap the server keeps in USD. A budget box speaks the currency the
   * reader picked, so the unit rides after the box, and a box in CNY says under itself what
   * it will actually store.
   */
  budgetUnit: (symbol: string): string => `${symbol} / 月`,
  budgetStoredAs: (amount: string): string => `存为 ${amount} / 月`,
  /** The 工位 group under the company sidebar's channel list: one row per employee. */
  sessionList: {
    desks: (n: number): string => `工位（${n}）`,
    deskOf: (name: string): string => `${name} 的工位`,
    running: "运行中",
    noEmployees: "这个组织还没有员工",
    untitledSession: "未命名会话",
    loadFailed: "员工列表加载失败",
  },
  overview: {
    title: "概览",
    info: "组织的全局一页：员工、看板、今日日程与本周期预算，以及需要你拍板的事。每块角上有一个按钮，点它进对应页面。",
    employees: "员工",
    onDesk: "在岗",
    running: "运行中",
    paused: "预算暂停",
    board: "看板",
    blocked: "被阻塞",
    today: "今日日程",
    todayEmpty: "今天没有日程",
    spend: "本周期支出",
    reviewTickets: "审核中的工单",
    alerts: "告警",
    alertsEmpty: "本周期没有预算告警",
    /** A fresh organization: point the user at the CEO. */
    firstStep: "组织刚建立：先打开 CEO 的工位会话，确认使命、招募员工并安排日程。",
    /** The hero: who made it, how big it is, which period the spend counts. */
    createdBy: (user: string): string => `由 ${user} 创建`,
    employeesCount: (n: number): string => `${n} 位员工`,
    period: (period: string): string => `${period} 周期`,
    openCeoDesk: "打开 CEO 工位",
    refreshFailed: "刷新失败，显示的是上次读取的数据",
    /** The hero's mission, clamped to one line until the toggle opens it. */
    mission: "使命",
    expand: "展开",
    collapse: "收起",
    /** The KPI strip. */
    openTickets: "未完结工单",
    boardTotal: (n: number): string => `共 ${n} 张`,
    todayCount: (n: number): string => `${n} 项`,
    upcoming: "待触发",
    failed: "未按时",
    budgetLeft: (amount: string): string => `剩余 ${amount}`,
    overBudget: (amount: string): string => `超支 ${amount}`,
    /** The corner button of a KPI cell and of the hero's spend block: where it jumps to. */
    openChart: "打开组织图",
    openBoard: "打开工单看板",
    openCalendar: "打开日历",
    openFinance: "打开财务",
    /** The tooltip of an inbox row's title: the row is inert, its title is what goes there. */
    openTicket: "查看工单",
    openChannel: "打开频道",
    /** The counts under the board bar: each opens the board filtered to the column it counts. */
    openColumn: (column: string): string => `查看「${column}」的工单`,
    /** The three first steps of a new organization (replaces the empty sections). */
    firstStepsTitle: "三步上手",
    firstStepsInfo:
      "组织刚建立时的引导：和 CEO 谈使命、招募员工、安排日程。招到第一位员工或开出第一张工单后，这里换成日常仪表盘。",
    stepCeoTitle: "和 CEO 谈使命",
    stepCeoBody: "打开 CEO 的工位会话，确认使命，让它提出组织结构与首批工单。",
    stepHireTitle: "招募员工",
    stepHireBody: "在组织图里为 CEO 招募下属：选已有 Agent 或新建一个，给头衔与预算。",
    stepScheduleTitle: "安排日程",
    stepScheduleBody: "在日历里为员工安排巡检：到点即向它的工位会话发送提示词。",
    stepDone: "已完成",
    goToChart: "去组织图",
    goToCalendar: "去日历",
    /** The inbox: what names the reader, what is stuck and what has landed, newest first. */
    inbox: "收件箱",
    inboxInfo:
      "按时间倒序列出组织要对你说的三件事：全员频道里 @我（或 @所有人）的消息、被阻塞的工单、本周期已完成的工单。其余的去频道与看板本身看。",
    inboxEmpty: "收件箱是空的",
    /** The filter chips over the rows, each with its own count. */
    inboxFilters: { all: "全部", mention: "@我", blocked: "阻塞", done: "已完成" },
    /** The chip that leads a row, naming what the row is. */
    inboxCategories: { mention: "@我", blocked: "阻塞", done: "已完成" },
    /** Today's timeline. */
    timelineMore: (n: number): string => `还有 ${n} 项，打开日历查看`,
  },
  calendarOutcomes: {
    fired: "已触发",
    queued: "排队",
    paused: "已暂停",
    missed: "已错过",
    error: "出错",
  } as Record<string, string>,
  chart: {
    title: "组织图",
    info: "员工树即汇报线：CEO 为根，每个节点是一位员工 Agent。节点右上角的菜单里是「打开工位会话」和人事操作，每一项人事操作都会改写组织图文件。画布可滚轮缩放、拖拽平移；点右上角的百分比回到适应窗口。",
    empty: "组织图为空",
    nodeMenu: "员工操作",
    hire: "招募下属",
    setBudget: "设预算",
    changeReportsTo: "调整汇报线",
    nameAndAvatar: "名字与头像",
    profileTitle: (name: string) => `名字与头像——${name}`,
    employeeName: "名字",
    employeeNameHint: (agentId: string) =>
      `大家在这个组织里怎么称呼这位员工，可以是中文；和 id（${agentId}）一样可以用在 @ 后面。两位员工同名时，会各自带上 id 作备注。留空则用 Agent 自己的名字。`,
    employeeNameHireHint:
      "大家在这个组织里怎么称呼这位员工，可以是中文；和 id 一样可以用在 @ 后面。留空则用 Agent 自己的名字。",
    renewDesk: "换工位",
    leave: "离任",
    ceoCannotLeave: "CEO 不能离任",
    invalidEntry: "该条目无效",
    workspaceTail: "工作区",
    /** Hire dialog. */
    hireTitle: (manager: string): string => `为 ${manager} 招募下属`,
    hireSource: "来源",
    hireExisting: "选择已有 Agent",
    hireNew: "新建 Agent",
    agent: "Agent",
    pickAgent: "选择 Agent…",
    noAgentsLeft: "本 Project 没有可招募的 Agent",
    agentId: "Agent id",
    agentIdHint: "2~64 位：小写字母开头，仅小写字母、数字与下划线",
    agentName: "名称",
    agentNameHint: "留空则使用 Agent id",
    agentDescription: "描述",
    plugins: "插件",
    pluginsHint: "缺省安装 agent-company（组织流程）与 agent-development（开发技能）",
    pluginsPlaceholder: "未选择插件",
    pluginsPicked: (n: number): string => `已选 ${n} 个插件`,
    pluginsEmpty: "插件库暂无可安装的插件",
    employeeTitle: "头衔",
    employeeTitlePlaceholder: "例如：文档工程师",
    duties: "职责",
    dutiesHint: "写进组织图，员工每次工作轮都会读到",
    workspace: "工作区",
    workspaceHint: "公共工作区下的子目录（`.` 为整个公共工作区），或一个已存在的绝对路径",
    /** Hiring: the same spec, with the default the server fills in when the field is left empty. */
    hireWorkspaceHint:
      "公共工作区下的子目录，或一个已存在的绝对路径；留空即以该员工的 Agent id 命名的子目录",
    budget: "月预算",
    budgetHint: "每月上限，留空为不限；口径是本人加全部下属的累计支出",
    hireConfirm: (name: string, manager: string): string =>
      `将 ${name} 加入组织，汇报给 ${manager}？会改写组织图文件。`,
    hired: (name: string): string => `已招募 ${name}`,
    /** Budget / reporting line / desk renewal / leave dialogs. */
    budgetTitle: (name: string): string => `设置 ${name} 的预算`,
    budgetConfirm: (name: string, budget: string): string =>
      `将 ${name} 的月预算改为 ${budget}？超过 80% 告警，达到 100% 暂停其自动触发。`,
    reportsToTitle: (name: string): string => `调整 ${name} 的汇报线`,
    reportsToConfirm: (name: string, manager: string): string =>
      `让 ${name} 改为汇报给 ${manager}？其下属随之一起移动。`,
    reportsToCycle: "不能汇报给自己或自己的下属",
    renewDeskTitle: (name: string): string => `为 ${name} 换工位`,
    renewDeskExplain: "换工位会开一个新的工位会话并重置上下文；改了工作区就写入员工树。",
    workspaceInvalid: "工作区无效：需要是公共工作区下的子目录，或一个已存在的绝对路径。",
    renewed: "已换到新的工位会话",
    leaveConfirm: (name: string): string =>
      `让 ${name} 离任？它会移出组织图，其下属改为汇报给它的上级；Agent 本身与所有会话保留。`,
    left: (name: string): string => `${name} 已离任`,
    saved: "组织图已更新",
    /** The page: the canvas and its zoom control, the legend, counts, a failed refresh, the detached row. */
    canvas: "组织图画布",
    zoom: "缩放",
    zoomIn: "放大",
    zoomOut: "缩小",
    zoomFit: "适应窗口",
    legend: "运行态图例",
    employeeCount: (n: number): string => `${n} 位员工`,
    spend: "本周期支出",
    refreshFailed: (error: string): string => `刷新失败：${error}`,
    detached: "上级不在组织图中",
    detachedNotice: (n: number): string =>
      `${n} 位员工的汇报线接不到 CEO：上级已离开组织，或汇报线成环。用「调整汇报线」把它们接回员工树。`,
    /** Hire and edit dialogs: the two sections, the current value, and the field hints. */
    hireAgentSection: "Agent",
    hirePositionSection: "职位",
    agentHint: "只列出本 Project 中尚未加入组织的 Agent",
    budgetPlaceholder: "例如 30",
    clearBudget: "设为不限",
    currentValue: (value: string): string => `当前：${value}`,
    manager: "上级",
    reportsToHint: "只列出不在其下属范围内的员工",
  },
  calendar: {
    title: "日历",
    info: "全员日程项的月 / 周 / 日视图。每条日程属于一位员工，到点即向它的工位会话发送提示词；颜色按员工区分，已过去的实例标出触发结果。日程驱动员工的工位会话按时巡检看板、推进工单，点右上角「新建日程」为某位员工安排一条。",
    month: "月",
    week: "周",
    day: "日",
    today: "今天",
    prev: "上一段",
    next: "下一段",
    allEmployees: "全部员工",
    filterEmployee: "按员工筛选",
    create: "新建日程",
    createTitle: "新建日程",
    editTitle: (name: string): string => `编辑日程「${name}」`,
    employee: "员工",
    name: "名称",
    nameHint: "即文件名（不含 .toml），创建后不可改",
    prompt: "提示词",
    enabled: "启用",
    startAt: "开始时间",
    endAt: "结束时间",
    period: "周期",
    periodHint: "30m / 12h / 7d，留空为一次性；最短 5m",
    delete: "删除日程",
    deleteConfirm: (name: string): string => `确认删除日程「${name}」？`,
    saveConfirm: (name: string): string => `保存日程「${name}」？会改写它的日程文件。`,
    outcome: "结果",
    lastFired: "最近触发",
    nextFire: "下次触发",
    past: "已过去",
    pausedNote: "已暂停：到点跳过，不触发",
    disabledNote: "已停用",
    invalidFiles: "解析失败的日程文件",
    empty: "还没有日程",
    emptyHint:
      "日程驱动员工的工位会话按时巡检看板、推进工单，点右上角「新建日程」为某位员工安排一条。",
    moreEvents: (n: number): string => `还有 ${n} 项`,
    /** The month cell's "+N more" is a button: its accessible name, and the day panel it opens. */
    moreEventsExpand: (n: number): string => `还有 ${n} 项，展开`,
    openDay: "查看当天",
    weekdays: ["周一", "周二", "周三", "周四", "周五", "周六", "周日"] as readonly string[],
    allDay: "全天",
    promptHint: "写下你希望员工在这一刻做的巡检，例如：检查看板、推进自己的工单、在频道汇报",
    monthTitle: (year: number, month: number): string => `${year} 年 ${month} 月`,
    /** How an event recurs, for the legend: the period read as a cadence with the time of day. */
    cadence: {
      once: "一次性",
      minutes: (n: number): string => `每 ${n} 分钟`,
      hours: (n: number): string => `每 ${n} 小时`,
      daily: (time: string): string => `每天 ${time}`,
      days: (n: number, time: string): string => `每 ${n} 天 ${time}`,
      weekly: (time: string): string => `每周 ${time}`,
      weeks: (n: number, time: string): string => `每 ${n} 周 ${time}`,
      invalid: "周期无效",
    },
    legendEmpty: "还没有日程",
    legendFilter: (name: string): string => `只看 ${name} 的日程`,
    createAt: (label: string): string => `在 ${label} 新建日程`,
    loadFailed: (error: string): string => `日历加载失败：${error}`,
    /** The "×" that puts the empty-calendar note away for good (the same sentence stays in the page's "?"). */
    dismissHint: "知道了",
    /** Under the start time: why two employees should not share one minute. */
    staggerHint:
      "错峰安排：给每位员工各自的时刻，不要让多位员工在同一分钟触发，避免争抢预算与工单。",
    /** Heads the advisory lines a calendar write answers with (the lines themselves come from the server, in English). */
    warningsPrefix: "排班提醒",
  },
  tickets: {
    title: "工单",
    info: "五列看板即工单的生命周期：提议 → 进行中 → 审核中 → 已完成 / 已拒绝。拖拽卡片移列，点卡片标题在原地弹出详情窗口；被阻塞的工单留在原列并带角标。工单是组织的工作单位：点右上角「新建工单」建一张并指定负责人，它的工位会话会为这张工单发起工单会话。",
    columns: {
      proposed: "提议",
      in_progress: "进行中",
      review: "审核中",
      done: "已完成",
      rejected: "已拒绝",
    } as Record<string, string>,
    blockedOnly: "只看被阻塞",
    create: "新建工单",
    createTitle: "新建工单",
    empty: "还没有工单",
    emptyHint:
      "工单是组织的工作单位：点右上角「新建工单」建一张并指定负责人，它的工位会话会为这张工单发起工单会话。",
    /** The "×" that puts the empty-board note away for good (the same sentence stays in the page's "?"). */
    dismissHint: "知道了",
    columnEmpty: "空",
    ticketTitle: "标题",
    goal: "目标",
    goalHint: "要达成什么，一段话即可",
    acceptance: "验收标准",
    acceptanceHint: "怎样算完成；审核时逐条核对",
    result: "结果",
    owner: "负责人",
    noOwner: "未指定",
    /** The create dialog's default owner: whoever is filing the ticket. */
    ownerSelf: "自己",
    ownerSelfHint: "留空则为自己",
    parent: "父工单",
    noParent: "无",
    notify: "通知人",
    notifyHint: "逗号分隔的主体，如 agent:ceo, user:alice；状态变化时通知",
    priority: "优先级",
    due: "截止",
    noDue: "无",
    blocked: "被阻塞",
    blockedReason: "阻塞原因",
    blockedBy: "等谁",
    blockedTooltip: (reason: string, by: string): string => `被阻塞：${reason}（等 ${by}）`,
    unblock: "解除阻塞",
    unblockConfirm: (title: string): string => `解除「${title}」的阻塞？`,
    block: "标记阻塞",
    blockTitle: "标记阻塞",
    blockReasonHint: "一句话说明卡在哪里",
    blockByHint: "等哪张工单或哪位主体",
    sessions: "关联工单会话",
    sessionsCount: (n: number): string => `${n} 个会话`,
    openSession: "打开会话",
    /** The row action of a child ticket, and the tooltip of every ticket title that opens one. */
    openTicket: "打开工单",
    progress: "进度",
    progressEmpty: "还没有进度记录",
    addProgress: "追加进度",
    progressPlaceholder: "一句话记下进展…",
    children: "子工单",
    childrenEmpty: "没有子工单",
    cost: "本单成本",
    rolledUpCost: "总成本",
    /** The card's muted parent line; the drawer names the parent in a labelled field instead. */
    parentLine: (title: string): string => `父工单：${title}`,
    moveTitle: "移动工单",
    moveConfirm: (title: string, column: string): string => `将「${title}」移到「${column}」？`,
    rejectReason: "拒绝理由",
    rejectReasonHint: "一句话说明为什么拒绝，记入工单的结果",
    moved: "工单已移动",
    invalid: "该工单无效：状态与所在列不符，或 id 重复",
    invalidFiles: "无法解析的工单文件",
    edit: "编辑字段",
    saveConfirm: (title: string): string => `保存对「${title}」的修改？会改写工单文件。`,
    saved: "工单已保存",
    created: "工单已创建",
    detail: "工单详情",
    /** Header control of the detail dialog: back to the ticket this one was opened from (a parent, a child). */
    back: "返回",
    dragHint: "拖到另一列即可移动",
    searchPlaceholder: "搜索标题或 id",
    searchNoMatch: "没有匹配的工单",
    dropHere: "拖到这里",
    overdue: "已逾期",
    summary: "基本信息",
    history: "操作历史",
    historyEmpty: "还没有操作记录",
    /** The frontmatter's history actions; a history line names one and nothing else. */
    historyActions: {
      created: "创建",
      assigned: "指派给",
      moved: "移到",
      blocked: "阻塞",
      unblocked: "解除阻塞",
      progress: "写进展",
      session_started: "发起会话",
      session_attached: "挂接会话",
      edited: "编辑",
    } as Record<string, string>,
    slug: "id 短名",
    slugHint: "小写英文单词用连字符连接，如 marketplace-site；不能有数字，留空则由标题生成",
    slugInvalid: "只能用小写英文单词，以连字符连接，不能有数字",
    noGoal: "还没有写目标",
    noAcceptance: "还没有写验收标准",
    noResult: "还没有结果",
    moveTo: "移到…",
    move: "移动",
    copyId: "复制工单 id",
    invalidTickets: "无效的工单",
    loadFailed: (error: string): string => `看板加载失败：${error}`,
  },
  finance: {
    title: "财务",
    info: "预算按员工设置，口径是本人加全部下属的累计支出；周期为自然月（组织时区）。达到 80% 告警，达到 100% 暂停该员工的自动触发。",
    period: "周期",
    thisPeriod: "本周期",
    prevPeriod: "上周期",
    total: "合计",
    unpriced: "* 部分用量使用了未配置价格的模型，成本为下限",
    budget: "预算",
    editBudget: "编辑预算",
    budgetPlaceholder: "不限",
    clearBudget: "清空",
    budgetSaved: "预算已更新",
    own: "本人支出",
    cumulative: "累计支出",
    /** The spend tree reads cumulative against budget in one column; own spend rides in the row tooltip. */
    cumulativeBudget: "累计成本 / 预算",
    ratio: "占比",
    warned: "已告警",
    paused: "已暂停",
    spendTree: "支出树",
    spendTreeInfo: "沿汇报线展开：累计支出包含全部下属，预算与占比按同一口径。",
    ticketsTable: "工单支出",
    ticketsInfo: "每张工单的贡献会话成本；总成本沿父工单累加。挂到多张工单的会话按份数分摊。",
    ticketsEmpty: "本周期没有工单支出",
    rolledUp: "总成本",
    /** The ledger's fold: child tickets are hidden until the parent's chevron opens them. */
    expandChildren: "展开子工单",
    collapseChildren: "收起子工单",
    childCount: (n: number): string => `${n} 张子工单`,
    trend: "趋势",
    alerts: "告警与暂停",
    alertsEmpty: "本周期没有告警",
    alertWarned: (name: string, at: string): string => `${name} 于 ${at} 达到预算 80%`,
    alertPaused: (name: string, at: string): string =>
      `${name} 于 ${at} 达到预算上限，已暂停自动触发`,
    alertsHint: "解除方式：调高该员工的预算，或清空预算；下一次巡检自动恢复。",
    /** The KPI row under the title. */
    kpiTotal: "合计支出",
    orgBudget: "组织预算（CEO）",
    kpiEmployees: "员工",
    budgetsSet: (n: number): string => `${n} 人设了预算`,
    thresholds: "达到 80% 告警，达到 100% 暂停",
    kpiAlerts: "告警",
    alertsSummary: (warned: number, paused: number): string => `${warned} 告警 · ${paused} 暂停`,
    /** Column header explanations, and the tree's root mark. */
    cumulativeInfo: "本人加全部下属的支出之和；预算与占比按这个口径。",
    rolledUpInfo: "本工单与子工单的成本之和。",
    root: "根",
    /** The inline budget editor. */
    budgetEmptyHint: "留空为不限",
    saveBudget: "保存预算",
    cancelEdit: "取消",
    editBudgetOf: (name: string): string => `编辑 ${name} 的预算`,
    /** The ticket table's owner column and row action. */
    openTicket: "打开工单",
    /** The trend section. */
    trendInfo: "组织全部会话每天的成本合计，按组织时区分日；只画有支出的日子。",
    trendEmpty: "本周期还没有支出记录",
    /** The alert list. */
    alertsInfo:
      "每次巡检核对累计支出与预算：达到 80% 记一次告警，达到 100% 暂停该员工及其下属的自动触发；解除后自动恢复。",
    pausedGroup: "已暂停自动触发",
    warnedGroup: "已告警",
    warnedAt: (at: string): string => `${at} 达到 80%`,
    pausedAt: (at: string): string => `${at} 达到 100%`,
    /** A refetch failed while the last good data is still on screen. */
    refreshFailed: "刷新失败，显示的是上次加载的数据",
  },
  /**
   * Channels — company mode's home surface. The sidebar lists them where development mode
   * lists conversations; the channel view holds the header, the message stream and the
   * composer. The all-hands channel's stored name is never shown: `allHands` is its label
   * everywhere.
   */
  channels: {
    /** The sidebar's list, its groups and the dialog above it. */
    listTitle: "频道",
    /** The phone drawer's hamburger, which opens the channel list (development mode names it S.chat.sessionList). */
    drawerLabel: "频道列表",
    allHands: "全员频道",
    mine: "我的频道",
    others: "其他频道",
    archivedGroup: "已归档",
    newChannel: "新建频道",
    noChannels: "还没有频道",
    loadFailed: "频道列表加载失败",
    join: "加入",
    joining: "加入中…",
    joined: "已加入频道",
    joinTitle: "加入频道",
    joinConfirm: "加入后你会收到这个频道里 @你 的消息，也能在这里发言。",
    /** A row's badges, and the sentence they lend to its accessible name. */
    mentionChip: "@我",
    badgeUnread: (n: number): string => `${n} 条未读`,
    badgeMentions: (n: number): string => `${n} 条 @我`,
    /** The channel header and what its controls do. */
    streamLabel: (name: string): string => `「${name}」的消息`,
    purpose: "主题",
    purposeEmpty: "还没有写主题",
    memberCount: (n: number): string => `${n} 人`,
    memberList: "频道成员",
    invite: "邀请",
    inviteTitle: "邀请到频道",
    inviteSearch: "搜索员工或成员",
    inviteEmpty: "没有可邀请的人了",
    invited: (name: string): string => `已邀请 ${name}`,
    leave: "离开",
    leaveTitle: "离开频道",
    leaveConfirm: (name: string): string =>
      `确认离开「${name}」？你仍然可以阅读，但不会再收到 @，也不能发言，直到重新加入。`,
    left: "已离开频道",
    channelMenu: "频道操作",
    rename: "重命名",
    renameTitle: "重命名频道",
    editPurpose: "改主题",
    purposeTitle: "修改频道主题",
    archive: "归档",
    unarchive: "取消归档",
    archiveTitle: "归档频道",
    archiveConfirm: (name: string): string =>
      `确认归档「${name}」？归档后频道只读，并折叠进「已归档」，随时可以取消归档。`,
    archived: "频道已归档",
    unarchived: "已取消归档",
    archivedNotice: "这个频道已归档，只读。取消归档后才能继续发言。",
    notMemberNotice: "你还不是这个频道的成员。加入后才能发言。",
    channelLoadFailed: "频道加载失败",
    /** The "?" beside the channel name, in its two kinds. */
    allHandsInfo:
      "全员频道随组织一起创建：组织里的每个人都在这里——每位员工、每位 Project 成员，你也在这里看——谁也不能退出，也不能归档；预算告警等系统通知都发在这里。",
    channelInfo:
      "受邀频道：员工只能由成员邀请进来，@ 也只在频道成员之间送达；人可以自行加入，并且可以阅读任何频道。",
    /** Why the all-hands channel's menu has no archive row; what that channel IS stays in the "?" above. */
    allHandsNoArchive: "全员频道不可归档",
    /** The new-channel dialog. */
    createTitle: "新建频道",
    creating: "创建中…",
    created: "频道已创建",
    idField: "频道 id",
    idHint: "2–64 个字符：小写字母开头，仅小写字母、数字和下划线",
    idReserved: "default_channel 留给全员频道",
    idTaken: "这个 id 已经被占用",
    nameField: "显示名",
    nameHint: "留空则用 id",
    purposeHint: "一句话说明这个频道是做什么的",
    /** The message stream. */
    empty: "还没有消息",
    emptyHint:
      "只有 @ 才会打扰员工：@某位员工 送进它的工位会话，@all 送给频道里所有成员；不带 @ 的消息只是留言。",
    placeholder: "输入消息，Enter 发送，Shift+Enter 换行，@ 提及成员",
    send: "发送",
    you: "你",
    mentionAll: "所有人",
    mentionAllDesc: "频道全部成员",
    employees: "员工",
    members: "成员",
    earlierDays: "更早的记录",
    ticketRef: (id: string): string => `工单 ${id}`,
    sessionRef: "查看会话",
    replyTo: "回复",
    /** The ref chips' tooltips: what the chip's own text does not say — where it lands. */
    openTicketRef: "查看工单",
    replyToJump: "跳到被回复的消息",
    hop: (n: number): string => `自动接力 · 第 ${n} 跳`,
    /** The chip's tooltip, and the one line about hops the channel header's "?" carries. */
    hopInfo:
      "这条消息由员工的工作轮自动发出，是一条 @ 连锁的第 N 跳：人或日程发起的消息是第 0 跳，员工被 @ 后在工作轮里的回复是第 1 跳（不标），再被 @ 的员工回复是第 2 跳……到达组织设置的连锁上限（缺省 3）后 @ 只记录、不再触发任何人，避免两个员工互相 @ 到天亮。",
    hopSummary:
      "被 @ 的员工在回复里再 @ 别人，就是一条 @ 连锁：从第 2 跳起消息会标出「自动接力 · 第 N 跳」，到达组织的连锁上限（缺省 3）后 @ 只记录、不再触发任何人。",
    /** Day separators, paging and the read cursor in the stream. */
    today: "今天",
    yesterday: "昨天",
    noEarlier: "没有更早的记录",
    unreadDivider: "以下为未读",
    newMessages: (n: number): string => `${n} 条新消息`,
    /** The composer's @ autocomplete. */
    mentionPanel: "提及",
    mentionsYou: "提到了你",
    /** Accessible name of a system banner and of a message's per-line time. */
    systemMessage: "系统消息",
    sentAt: (time: string): string => `发送于 ${time}`,
    /**
     * The system lines, one sentence per kind the server records (features/company/channel-notices.ts).
     * Principals arrive already resolved to display names; a period is `yyyy-mm` and the money
     * figures are the server's own, in USD.
     */
    notices: {
      employee_joined: (agent: string, title: string, manager: string): string =>
        `${agent} 以「${title}」身份加入，汇报给 ${manager}。`,
      employee_left: (agent: string, manager: string): string =>
        `${agent} 已离开组织，其下属改为汇报给 ${manager}。`,
      channel_created: (by: string): string => `${by} 创建了这个频道。`,
      channel_archived: (by: string): string => `${by} 归档了这个频道。`,
      channel_unarchived: (by: string): string => `${by} 取消了这个频道的归档。`,
      channel_joined: (principal: string): string => `${principal} 加入了频道。`,
      channel_invited: (by: string, principal: string): string =>
        `${by} 邀请 ${principal} 加入了频道。`,
      channel_left: (principal: string): string => `${principal} 离开了频道。`,
      channel_removed: (by: string, principal: string): string =>
        `${by} 把 ${principal} 移出了频道。`,
      budget_warned: (
        agent: string,
        percent: string,
        period: string,
        cost: string,
        budget: string,
      ): string =>
        `预算提醒：${agent} 已用掉 ${period} 预算的 ${percent}%（${cost} / ${budget} USD）。`,
      budget_paused: (
        agent: string,
        percent: string,
        period: string,
        cost: string,
        budget: string,
      ): string =>
        `预算暂停：${agent} 已达到 ${period} 预算的 ${percent}%（${cost} / ${budget} USD）。它与下属的日历已暂停，直到下个月或调高预算；@ 提及和直接对话仍然可用。`,
      ticket_blocked: (ticket: string, title: string): string =>
        `工单 ${ticket}（${title}）被阻塞了。`,
      ticket_done: (ticket: string, title: string): string => `工单 ${ticket}（${title}）已完成。`,
      ticket_rejected: (ticket: string, title: string): string =>
        `工单 ${ticket}（${title}）已被拒绝。`,
    },
  },
  /** The handbook page: the knowledge base directory, its index and its documents. */
  handbook: {
    info: "组织的知识库：handbook/ 目录下的 Markdown 文档。索引（README.md）是每次触发都会让员工 Agent 先读的那一页，其余文档由索引列出、按需再读。",
    /** The pinned first row: the index, and why it is pinned. */
    indexLabel: "索引 · 每轮先读",
    documents: "文档",
    /** The tree's own controls: closing every folder, and what a folder row's count means. */
    collapseAll: "全部折叠",
    documentsInFolder: (n: number): string => `${n} 篇文档`,
    noOtherDocuments: "还没有其他文档。新建一篇，并在索引里列出它。",
    emptyDocument: "这篇文档还是空的。",
    newDocument: "新建文档",
    creating: "创建中…",
    pathField: "路径",
    pathPlaceholder: "decisions/2026-09-02-hire-plan.md",
    pathHint:
      "相对于 handbook/ 的路径，用 / 分层；每段以字母或数字开头，仅字母、数字、. _ -；省略扩展名时补 .md。",
    pathInvalid: "路径无效：每段以字母或数字开头，仅字母、数字、. _ -，用 / 分层，最多八层。",
    pathExists: "该文档已存在。",
    documentCreated: "文档已创建",
    deleteDocument: "删除文档",
    deleteConfirm: (path: string): string =>
      `删除 ${path}？文档会从 handbook/ 目录移除；索引里指向它的条目不会自动更新。`,
    documentDeleted: "文档已删除",
    loadFailed: "手册加载失败",
    documentLoadFailed: "文档加载失败",
    /** A row's tooltip: when the file was last written, and its size. */
    updatedAt: (time: string, size: string): string => `更新于 ${time} · ${size}`,
    /** Beside the editor's buttons: what the text is, and the shortcut. */
    editorHint: "Markdown · Ctrl/⌘+S 保存",
  },
  /** The proposals page (the company-proposals plugin): the queue, one proposal's detail, its comments and the actions on it. */
  proposals: {
    title: "提案",
    info: "一份提案是一件改动的说明：拟改的接口、改法、目的与一个测试例，由员工来写并同时实施，PR 挂在关联材料里。选中正文里的一段文字即可评论，再点「请求整改」一次发给作者；认可即请求合并。链接写作 proposal:<编号>。",
    newProposal: "新建提案",
    newTitle: "新建提案",
    author: "作者",
    authorHint: "写这份提案的员工；你的委托会直接送到它的工位",
    brief: "委托",
    briefHint: "要改什么、为什么，一两句即可",
    titleField: "标题",
    titleHint: "作者写提案时定",
    created: (n: number): string => `提案 #${n} 已创建`,
    queue: "队列",
    search: "搜索提案",
    searchPlaceholder: "搜索：is:open author:… 关键词",
    /** The filter chips under the search box: lifecycle states, all, and the unread toggle. */
    chip: {
      group: "按状态筛选",
      open: "进行中",
      ready: "就绪",
      approved: "已认可",
      merged: "已合并",
      rejected: "已拒绝",
      all: "全部",
      unread: "有未读",
    },
    noMatch: (q: string): string => `没有匹配「${q}」的提案`,
    showAll: "显示全部",
    queueEmpty: "还没有提案",
    queueEmptyHint:
      "点右上角「新建提案」，把一件改动委托给一名员工：它写提案，另一名员工同时实施。",
    dismissHint: "知道了",
    notFound: "提案不存在",
    pickOne: "从队列选一份提案",
    backToQueue: "返回提案列表",
    updated: "更新于",
    loadFailed: "提案加载失败",
    unreadBadge: (n: number): string => `${n} 条未读`,
    unreadNote: (n: number): string => `${n} 条未读事件`,
    status: {
      drafting: "起草中",
      ready: "已就绪",
      approved: "已认可",
      merged: "已合并",
      rejected: "已拒绝",
    } as Record<string, string>,
    revision: (n: number): string => `第 ${n} 修订`,
    /** The panel above the body while an older approval stands: what changed since it. */
    diff: {
      title: (approved: number, head: number): string =>
        `自认可的第 ${approved} 修订以来已修订（→ 第 ${head} 修订）`,
      approvedBy: (who: string, when: string): string => `${who} 认可于 ${when}`,
      hint: "认可只覆盖一个修订：作者又发了新修订，需要重新认可。",
      view: { label: "显示方式", changes: "改动", latest: "最新" },
      sectionAdded: "新增",
      sectionRemoved: "已删去",
      addedLabel: "新增",
      removedLabel: "已删去",
      changedLabel: "有改动",
      loadFailed: "读取认可的修订失败",
    },
    noRevision: "尚未发布",
    implementer: "实施者",
    noImplementer: "尚未指定",
    delegatedBy: "委托人",
    briefSection: "委托",
    materials: "关联材料",
    materialsEmpty: "还没有关联材料——实施者开出 PR 后挂在这里。",
    materialKind: {
      pr: "PR",
      issue: "Issue",
      branch: "分支",
      doc: "文档",
      ticket: "工单",
      url: "链接",
    } as Record<string, string>,
    /** A `pr` material's state on GitHub. */
    materialStatus: {
      draft: "草稿",
      open: "待合并",
      merged: "已合并",
      closed: "已关闭",
    } as Record<string, string>,
    scope: "范围",
    scopeEmpty: "作者尚未列出拟改的文件。",
    scopeFile: "文件",
    openFile: "在提案右侧打开",
    filePanel: {
      label: "文件",
      close: "关闭文件",
      copyPath: "复制路径",
      resize: "调整文件面板宽度",
      loadFailed: "读不到这个文件",
      binary: "二进制文件，这里不显示",
      truncated: "只显示前 512 KB",
      matches: (n: number) => `${n} 行匹配`,
      noMatch: "没有一行匹配这个名称模式",
    },
    scopePattern: "名称模式",
    scopeRoot: "仓库目录",
    scopeWorkspace: "共享工作区",
    scopeKind: { edit: "修改", new: "新建", delete: "删除", rename: "改名" },
    scopeState: {
      exists: "存在",
      new: "未创建",
      missing: "不存在",
      deleted: "已删除",
      renamed: "待改名",
    },
    scopeMissingHint: (where: string): string => `在 ${where} 下找不到这个文件`,
    tests: "测试",
    testsEmpty: "作者尚未列出相关的测试。",
    testKind: { existing: "已有", new: "拟增", delete: "删除" },
    testMissing: "文件不存在",
    testMissingHint: (where: string): string => `标为已有，但在 ${where} 下找不到这个文件`,
    testsShowMore: (n: number): string => `再显示 ${n} 条`,
    testsShowLess: "收起",
    testGroupToggle: (group: string): string => `折叠或展开 ${group} 组`,
    testGroupsUndeclared: "未声明的分组",
    testGroupsUndeclaredNote:
      "这些分组已不在「设置 → 插件 → 公司提案」的声明中，下次发布须把其中的测试移到已声明的分组。",
    sections: "正文",
    sectionsEmpty: "作者还没有发布正文。",
    events: "事件",
    sessions: "实施会话",
    openSession: "打开会话",
    discussions: "讨论",
    discuss: "讨论",
    discussHint: (who: string): string =>
      `以 ${who} 开一个临时会话讨论这份提案；结论只送到它的工位一次`,
    discussOpened: "已开讨论会话",
    discussionOpen: "进行中",
    discussionConcluded: "已送出结论",
    comment: "评论",
    comments: (n: number): string => `${n} 条评论`,
    commentPlaceholder: "对这段文字说点什么…",
    commentSelection: "评论所选文字",
    commentParagraph: "评论这一段",
    selectionHint: "选中正文里的一段文字即可评论",
    selectedText: "所选文字",
    selectionNotPlaced: "没能在正文里定位所选文字，请重新选择。",
    sectionComments: (n: number): string => `本节 ${n} 条评论`,
    staleComments: "旧修订上的评论",
    commentedOn: (quote: string): string => `「${quote}」`,
    addComment: "添加评论",
    commentEdited: "评论已更新",
    commentDeleted: "评论已撤回",
    commentAdded: "评论已记下，点「请求整改」发给作者",
    pending: "待发",
    resolved: "已解决",
    resolvedNote: (text: string): string => `已解决：${text}`,
    fromRevision: (n: number): string => `第 ${n} 修订的文字`,
    showResolved: (n: number): string => `${n} 条已解决`,
    requestChanges: (n: number): string => (n > 0 ? `请求整改（${n}）` : "请求整改"),
    requestChangesTitle: "请求整改",
    requestChangesConfirm: (n: number): string =>
      `把 ${n} 条待发评论合成一批发给作者？作者会逐条处理并发布新的修订。`,
    changesRequested: "已发给作者",
    approve: "认可并请求合并",
    approveTitle: "认可提案",
    approveConfirm: (title: string): string => `认可「${title}」并请求合并？实施者会把它合入主干。`,
    approved: "已认可，已通知实施者合并",
    reject: "拒绝",
    rejectTitle: "拒绝提案",
    rejectConfirm: (title: string): string => `拒绝「${title}」？`,
    rejectReason: "理由",
    rejectReasonHint: "一句话，记在事件里，作者能看到",
    rejected: "已拒绝",
    markMerged: "标记已合并",
    markMergedTitle: "标记已合并",
    markMergedConfirm: (title: string): string => `把「${title}」标记为已合并？`,
    merged: "已标记为已合并",
    /** One line per event on the timeline, by kind. */
    event: {
      notify_failed: "有人没收到通知",
      created: "创建了提案",
      revised: (n: number): string => `发布了第 ${n} 修订`,
      ready: "标记为已就绪",
      changes_requested: (n: number): string => `请求整改（${n} 条评论）`,
      implementation_started: (who: string): string => `请 ${who} 开始实施`,
      material_added: (label: string): string => `添加了材料 ${label}`,
      feedback: "发来实施反馈",
      runtime_feedback: "发来运行时反馈",
      resolved: "解决了一条评论",
      approved: "认可并请求合并",
      merged: "报告已合并",
      rejected: "拒绝了提案",
      brief_edited: "改写了简介",
      discussion_started: (who: string): string => `开了与 ${who} 的讨论`,
      discussion_concluded: "把讨论的结论送到了负责人的工位",
    },
    /** The capsule a `proposal:<n>` reference renders as: number, title, and the unread count when there is one. */
    capsule: (n: number, title: string): string => `#${n} ${title}`,
    capsuleUnread: (n: number): string => `${n} 条未读`,
    openProposal: "打开提案",
  },
};

export type CompanyStrings = typeof companyZh;

export const companyEn: CompanyStrings = {
  /** The mode switch (top-left of the sidebar, above the Project switcher) and its two options. */
  workMode: "Work mode",
  modeDev: "Development",
  modeCompany: "Company",
  switchToCompany: "Switch to company mode",
  switchToDev: "Switch to development mode",
  /**
   * Company mode is a beta, said in three shapes: the mini tag at the top-right of 「公司」 in
   * the work-mode switch (and the suffix the collapsed rail's tooltip carries in its place),
   * the tag's own tooltip, and the one sentence shown both under the admin's master switch
   * and as the notice a person gets the first time they enter the mode.
   */
  beta: "Beta",
  betaTitle: "Company mode is in beta and may be unstable.",
  betaNotice: "Beta: it may be unstable; please report what you hit.",
  /** The organization switcher that replaces the Project switcher in company mode. */
  switcher: "Organization",
  noOrganizations: "No organizations yet",
  createOrg: "New organization",
  orgSettings: "Organization settings",
  orgInvalid: "Invalid configuration",
  orgPaused: "Paused",
  /** The switcher's check mark beside the open organization (sr text). */
  switcherCurrent: "Current organization",
  /** `<project> / <org>` in the switcher: the Project half of the label. */
  inProject: (project: string, org: string): string => `${project} / ${org}`,
  /** The empty landing of `/org` when the user has no organization anywhere. */
  landingTitle: "Company mode",
  landingBody:
    "An organization is a group of employee Agents working along a reporting line: a CEO, the employees it hires, a shared board and its channels, and the calendar that drives them. Create one and start by talking to the CEO about its mission.",
  /** The page a stale deep link lands on: the organization it names is gone. */
  orgGoneTitle: "Organization not found",
  orgGoneBody:
    "It may have been deleted, or you may no longer have access to the Project it belongs to.",
  backToOrgs: "Back to organizations",
  /** Create dialog. */
  createTitle: "New organization",
  orgId: "Organization id",
  orgIdHint:
    "2–64 characters: a lowercase letter, then lowercase letters, digits or underscores; also the directory name, fixed once created",
  displayName: "Display name",
  displayNameHint: "Leave empty to use the organization id",
  mission: "Mission",
  missionHint:
    "One sentence on why this organization exists; the CEO's first session starts from it",
  missionPlaceholder:
    "e.g. Maintain the PenguinHarness docs site and publish a weekly update digest",
  /** The three examples under the mission field (org-examples.ts holds their order). */
  missionExampleHint: "Click to fill the mission",
  missionExamples: {
    research: {
      name: "Research Paper Lab",
      mission:
        "Set up a company that does research for me and produces papers fit for top-tier conferences. Experiments run autoresearch-style: fix the evaluation script and the metric first, edit one file only, give every experiment the same time budget, log each result as one line and keep only the changes that improve the metric. Before any experiment loop starts, the researcher asks me in the channel for resources — the machine and its GPU/CPU, concurrency, total hours, disk and data, paid APIs — then runs unattended inside what I approved and asks again before exceeding it. Papers go through adversarial review between two kinds of employee: reviewers reproduce the results, check baselines and ablations, hunt for test-set leakage and metric gaming, and return a score with required changes; authors revise or rebut point by point until the reviewer accepts.",
    },
    agentTuning: {
      name: "Agent Tuning Studio",
      mission:
        "Set up a company that optimizes my product Agent: raise its accuracy in real business use and improve the product experience.",
    },
    cloudReseller: {
      name: "Cloud Service Reseller",
      mission:
        "Set up a company that runs a cloud-service-style website for me: collect every low-priced service on the market, bundle and resell them at a markup to make money, and grow the site's SEO and visibility.",
    },
    mirror: {
      name: "Digital-twin company",
      mission:
        "Set up a company that mirrors our real company: I will give the CEO our real org chart and the CEO creates one digital twin per real employee; each twin's desk session is bound to that colleague's Feishu bot. A twin only receives its own colleague's messages by default, answers what it can on its own and relays the rest to the relevant colleague's twin, who passes it on to the real person. The CEO hires nobody on its own, schedules nothing and files no tickets; the company only relays and solves what it can.",
    },
  },
  createdOpeningCeo: "Organization created — opening the CEO's desk session",
  /** Create and settings dialogs: the model and the shared workspace, both optional. */
  modelField: "Model",
  modelInfo:
    "The model desk and ticket sessions run on by default; an employee given its own model in the org chart uses that instead. Takes effect from the next work round.",
  modelHint: "Leave empty to use the Project's default model",
  modelClear: "Back to the Project default",
  modelStale: "This model is no longer in the Project's model list",
  modelProjectDefault: "Project default",
  modelProjectDefaultNamed: (name: string): string => `Project default (${name})`,
  modelsLoadFailed:
    "The model list could not be read; you can still create with the Project default",
  machineCompanyModeOff:
    "Company mode is off on that machine. Turn it on in that machine's Settings first, then create the organization on it.",
  workspaceField: "Company workspace",
  workspaceInfo:
    "The directory the employees work in together: each employee's workspace is one of its sub-directories (or all of it), and desk and ticket sessions run inside it. It can be on one of the Project's connected machines: the organization then runs on that machine — its Agents and Sessions are there — and still belongs to this Project, which keeps a copy of its files. It cannot be moved afterwards.",
  workspaceHint:
    "Leave empty for the organization's own workspace/ directory; a path must be an existing directory, on this server or on a connected machine",
  workspaceEmpty: "The organization's own workspace/ directory",
  workspaceMenuHint: "Pick an existing directory as the company workspace",
  workspaceClear: "Back to the organization's own directory",
  /** CEO budget field (create dialog): the CEO's ceiling is the company's, since everyone reports to it. */
  ceoBudget: "CEO budget",
  ceoBudgetHint: "A monthly cap; the CEO's budget is the whole company's",
  /** The create dialog's draft (org-draft.ts): restored on reopen, dropped on create or on demand. */
  draftRestored: "Restored the draft you had not submitted",
  clearDraft: "Clear draft",
  creating: "Creating…",
  /** Settings dialog (the switcher's entry). */
  settingsTitle: "Organization settings",
  timezone: "Timezone",
  timezoneHint:
    "An IANA timezone such as Asia/Shanghai; budget periods (calendar months) and channel day files follow it",
  language: "Working language",
  languageInfo:
    "The language the organization works in: its handbook, the employee briefs, the CEO's initialization session and every desk's output are written in it; it is detected from the mission when the organization is created.",
  languages: {
    zh: "中文",
    en: "English",
  },
  approvalMode: "Approval mode",
  approvalModeInfo:
    "How tool calls in desk and ticket sessions are approved. Unattended runs never stop to ask a person, so there is no always-ask here.",
  approvalModes: {
    "allow-all": "Allow all",
    "read-only": "Read only",
    "deny-all": "Deny all",
  } as Record<string, string>,
  status: "Status",
  statusActive: "Active",
  statusPaused: "Paused",
  pause: "Pause organization",
  resume: "Resume organization",
  deleteOrg: "Delete organization",
  deleteOrgDesc:
    "Moves the organization to the Project's trash. Its employees stay as Agents and its conversations are kept.",
  deleteOrgConfirm:
    "The organization disappears from company mode. Its files go to the Project's trash (organizations/.trash) and can be moved back by hand. Its employees remain Agents of the Project; its desk and ticket conversations are kept, but with the organization gone no page lists them any more. Its id can be reused only after the old CEO's Agent is deleted. To stop an organization without losing anything, pause it instead.",
  deleteOrgTypeId: (orgId: string) => `Type ${orgId} to confirm`,
  deleted: (orgId: string) => `Organization ${orgId} deleted`,
  pauseInfo:
    "Paused stops every automatic trigger — calendar events no longer fire and @-mentions are not delivered to employees; you can still open any desk session and talk directly. An organization is paused, never deleted: its conversations, employees and tickets stay reachable.",
  settingsLoadFailed: "The organization's settings could not be read",
  /** Employee state dot, and the CEO mark. */
  employeeStates: {
    running: "Running",
    idle: "On desk",
    paused: "Budget paused",
  } as Record<string, string>,
  ceo: "CEO",
  reportsTo: (name: string): string => `Reports to ${name}`,
  openDesk: "Open desk session",
  openingDesk: "Opening the desk session…",
  /** Principals as the chat and tickets name them. */
  principalSystem: "System",
  principalAll: "Everyone",
  /** Spend against a budget, and the unbounded case. */
  spendOfBudget: (spend: string, budget: string): string => `${spend} / ${budget}`,
  noBudget: "Unbounded",
  budgetUnit: (symbol: string): string => `${symbol} / month`,
  budgetStoredAs: (amount: string): string => `Stored as ${amount} / month`,
  /** The 工位 group under the company sidebar's channel list: one row per employee. */
  sessionList: {
    desks: (n: number): string => `Desks (${n})`,
    deskOf: (name: string): string => `${name}'s desk`,
    running: "Running",
    noEmployees: "This organization has no employees yet",
    untitledSession: "Untitled session",
    loadFailed: "The employee list could not be loaded",
  },
  overview: {
    title: "Overview",
    info: "The organization on one page: employees, the board, today's calendar and this period's budget, plus what needs your decision. A corner button on each block opens its page.",
    employees: "Employees",
    onDesk: "On desk",
    running: "Running",
    paused: "Budget paused",
    board: "Board",
    blocked: "Blocked",
    today: "Today's calendar",
    todayEmpty: "Nothing scheduled today",
    spend: "This period's spend",
    reviewTickets: "Tickets in review",
    alerts: "Alerts",
    alertsEmpty: "No budget alerts this period",
    /** A fresh organization: point the user at the CEO. */
    firstStep:
      "The organization is brand new: open the CEO's desk session to confirm the mission, hire employees and set up the calendar.",
    /** The hero: who made it, how big it is, which period the spend counts. */
    createdBy: (user: string): string => `Created by ${user}`,
    employeesCount: (n: number): string => `${n} employee${n === 1 ? "" : "s"}`,
    period: (period: string): string => `Period ${period}`,
    openCeoDesk: "Open the CEO's desk",
    refreshFailed: "The refresh failed; this is the last data read",
    /** The hero's mission, clamped to one line until the toggle opens it. */
    mission: "Mission",
    expand: "Expand",
    collapse: "Collapse",
    /** The KPI strip. */
    openTickets: "Open tickets",
    boardTotal: (n: number): string => `${n} in total`,
    todayCount: (n: number): string => `${n} event${n === 1 ? "" : "s"}`,
    upcoming: "Upcoming",
    failed: "Not on time",
    budgetLeft: (amount: string): string => `${amount} left`,
    overBudget: (amount: string): string => `${amount} over`,
    /** The corner button of a KPI cell and of the hero's spend block: where it jumps to. */
    openChart: "Open the org chart",
    openBoard: "Open the ticket board",
    openCalendar: "Open the calendar",
    openFinance: "Open finance",
    /** The tooltip of an inbox row's title: the row is inert, its title is what goes there. */
    openTicket: "Open the ticket",
    openChannel: "Open the channel",
    /** The counts under the board bar: each opens the board filtered to the column it counts. */
    openColumn: (column: string): string => `Open the "${column}" tickets`,
    /** The three first steps of a new organization (replaces the empty sections). */
    firstStepsTitle: "First steps",
    firstStepsInfo:
      "The guide for a brand-new organization: talk to the CEO about the mission, hire, schedule. Once the first employee is hired or the first ticket filed, the dashboard takes its place.",
    stepCeoTitle: "Talk to the CEO",
    stepCeoBody:
      "Open the CEO's desk session, confirm the mission and let it propose the structure and the first tickets.",
    stepHireTitle: "Hire employees",
    stepHireBody:
      "On the org chart, hire subordinates for the CEO: an existing Agent or a new one, with a title and a budget.",
    stepScheduleTitle: "Schedule the work",
    stepScheduleBody:
      "On the calendar, give employees their rounds: when one is due, its prompt goes to the employee's desk session.",
    stepDone: "Done",
    goToChart: "Open the org chart",
    goToCalendar: "Open the calendar",
    /** The inbox: what names the reader, what is stuck and what has landed, newest first. */
    inbox: "Inbox",
    inboxInfo:
      "The three things the organization has to tell you, newest first: messages naming you (or everyone) in the all-hands channel, blocked tickets, and the tickets closed as done this period. For anything else, read the channel and the board themselves.",
    inboxEmpty: "Nothing in the inbox.",
    /** The filter chips over the rows, each with its own count. */
    inboxFilters: { all: "All", mention: "@me", blocked: "Blocked", done: "Done" },
    /** The chip that leads a row, naming what the row is. */
    inboxCategories: { mention: "@me", blocked: "Blocked", done: "Done" },
    /** Today's timeline. */
    timelineMore: (n: number): string => `${n} more — open the calendar`,
  },
  calendarOutcomes: {
    fired: "Fired",
    queued: "Queued",
    paused: "Paused",
    missed: "Missed",
    error: "Error",
  } as Record<string, string>,
  chart: {
    title: "Org Chart",
    info: "The employee tree is the reporting line: the CEO at the root, every node an employee Agent. The menu in a node's top-right corner opens its desk session and holds the personnel actions, each of which rewrites the chart file. The canvas zooms with the wheel and pans by dragging; click the percentage to fit the whole chart in the window again.",
    empty: "The chart is empty",
    nodeMenu: "Employee actions",
    hire: "Hire a subordinate",
    setBudget: "Set budget",
    changeReportsTo: "Change reporting line",
    nameAndAvatar: "Name and avatar",
    profileTitle: (name: string) => `Name and avatar — ${name}`,
    employeeName: "Name",
    employeeNameHint: (agentId: string) =>
      `What people call this employee here, in any language; it works after @ like the id (${agentId}). Two employees with the same name are shown with their ids noted. Empty: the Agent's own name.`,
    employeeNameHireHint:
      "What people call this employee here, in any language — it works after @ like the id. Empty: the Agent's own name.",
    renewDesk: "New desk session",
    leave: "Leave the organization",
    ceoCannotLeave: "The CEO cannot leave",
    invalidEntry: "This entry is invalid",
    workspaceTail: "Workspace",
    /** Hire dialog. */
    hireTitle: (manager: string): string => `Hire a subordinate for ${manager}`,
    hireSource: "Source",
    hireExisting: "Pick an existing Agent",
    hireNew: "Create a new Agent",
    agent: "Agent",
    pickAgent: "Pick an Agent…",
    noAgentsLeft: "No Agent in this Project is left to hire",
    agentId: "Agent id",
    agentIdHint:
      "2–64 characters: a lowercase letter, then lowercase letters, digits or underscores",
    agentName: "Name",
    agentNameHint: "Leave empty to use the Agent id",
    agentDescription: "Description",
    plugins: "Plugins",
    pluginsHint:
      "agent-company (the organization procedures) and agent-development (development skills) are installed by default",
    pluginsPlaceholder: "No plugins picked",
    pluginsPicked: (n: number): string => `${n} plugin${n === 1 ? "" : "s"} picked`,
    pluginsEmpty: "The plugin library has nothing to install",
    employeeTitle: "Title",
    employeeTitlePlaceholder: "e.g. Docs engineer",
    duties: "Duties",
    dutiesHint: "Written into the chart; the employee reads it at every work run",
    workspace: "Workspace",
    workspaceHint:
      "A sub-directory of the shared workspace (`.` for all of it), or an absolute path that already exists",
    /** Hiring: the same spec, with the default the server fills in when the field is left empty. */
    hireWorkspaceHint:
      "A sub-directory of the shared workspace, or an absolute path that already exists; left empty, a sub-directory named after the employee's Agent id",
    budget: "Monthly budget",
    budgetHint:
      "A monthly cap, leave empty for unbounded; counts the employee plus every subordinate",
    hireConfirm: (name: string, manager: string): string =>
      `Add ${name} to the organization, reporting to ${manager}? This rewrites the chart file.`,
    hired: (name: string): string => `Hired ${name}`,
    /** Budget / reporting line / desk renewal / leave dialogs. */
    budgetTitle: (name: string): string => `Set the budget of ${name}`,
    budgetConfirm: (name: string, budget: string): string =>
      `Set the monthly budget of ${name} to ${budget}? Past 80% warns; at 100% its automatic triggers pause.`,
    reportsToTitle: (name: string): string => `Change who ${name} reports to`,
    reportsToConfirm: (name: string, manager: string): string =>
      `Have ${name} report to ${manager}? Its subordinates move along with it.`,
    reportsToCycle: "Cannot report to itself or to one of its own subordinates",
    renewDeskTitle: (name: string): string => `A new desk session for ${name}`,
    renewDeskExplain:
      "A new desk session opens with a fresh context; a changed workspace is written to the org chart.",
    workspaceInvalid:
      "Invalid workspace: it must be a sub-directory of the shared workspace, or an absolute path that already exists.",
    renewed: "Moved to a new desk session",
    leaveConfirm: (name: string): string =>
      `Have ${name} leave? It is removed from the chart and its subordinates report to its manager instead; the Agent and every session are kept.`,
    left: (name: string): string => `${name} has left`,
    saved: "Chart updated",
    /** The page: the canvas and its zoom control, the legend, counts, a failed refresh, the detached row. */
    canvas: "Org chart canvas",
    zoom: "Zoom",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    zoomFit: "Fit to window",
    legend: "State legend",
    employeeCount: (n: number): string => `${n} employee${n === 1 ? "" : "s"}`,
    spend: "This period's spend",
    refreshFailed: (error: string): string => `Refresh failed: ${error}`,
    detached: "Manager not in the chart",
    detachedNotice: (n: number): string =>
      `${n} employee${n === 1 ? "" : "s"} cannot reach the CEO along the reporting line: the manager left the organization, or the line loops. Use "Change reporting line" to reattach them.`,
    /** Hire and edit dialogs: the two sections, the current value, and the field hints. */
    hireAgentSection: "Agent",
    hirePositionSection: "Position",
    agentHint: "Only Agents of this Project not yet in the organization",
    budgetPlaceholder: "e.g. 30",
    clearBudget: "Set unbounded",
    currentValue: (value: string): string => `Current: ${value}`,
    manager: "Manager",
    reportsToHint: "Only employees outside its own subtree are listed",
  },
  calendar: {
    title: "Calendar",
    info: "Every employee's calendar events in a month / week / day view. Each event belongs to one employee and sends its prompt to that employee's desk session when due; colours tell employees apart, and past instances show what the trigger did. Calendar events drive employees' desk sessions to check the board and push tickets on time; use New event, top right, to schedule one for an employee.",
    month: "Month",
    week: "Week",
    day: "Day",
    today: "Today",
    prev: "Previous",
    next: "Next",
    allEmployees: "All employees",
    filterEmployee: "Filter by employee",
    create: "New event",
    createTitle: "New calendar event",
    editTitle: (name: string): string => `Edit event "${name}"`,
    employee: "Employee",
    name: "Name",
    nameHint: "The file name (without .toml); fixed once created",
    prompt: "Prompt",
    enabled: "Enabled",
    startAt: "Start",
    endAt: "End",
    period: "Period",
    periodHint: "30m / 12h / 7d, empty for a one-off; 5m at the shortest",
    delete: "Delete event",
    deleteConfirm: (name: string): string => `Delete event "${name}"?`,
    saveConfirm: (name: string): string => `Save event "${name}"? This rewrites its calendar file.`,
    outcome: "Outcome",
    lastFired: "Last fired",
    nextFire: "Next fire",
    past: "Past",
    pausedNote: "Paused: due slots are skipped, not fired",
    disabledNote: "Disabled",
    invalidFiles: "Calendar files that failed to parse",
    empty: "No events yet",
    emptyHint:
      "Calendar events drive employees' desk sessions to check the board and push tickets on time; use New event, top right, to schedule one for an employee.",
    moreEvents: (n: number): string => `${n} more`,
    /** The month cell's "+N more" is a button: its accessible name, and the day panel it opens. */
    moreEventsExpand: (n: number): string => `${n} more, expand`,
    openDay: "Open the day",
    weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"] as readonly string[],
    allDay: "All day",
    promptHint:
      "What the employee should sweep at this moment, e.g. check the board, push its tickets, report in a channel",
    monthTitle: (year: number, month: number): string =>
      `${
        [
          "January",
          "February",
          "March",
          "April",
          "May",
          "June",
          "July",
          "August",
          "September",
          "October",
          "November",
          "December",
        ][month - 1] ?? month
      } ${year}`,
    /** How an event recurs, for the legend: the period read as a cadence with the time of day. */
    cadence: {
      once: "One-off",
      minutes: (n: number): string => `Every ${n} min`,
      hours: (n: number): string => `Every ${n} h`,
      daily: (time: string): string => `Daily ${time}`,
      days: (n: number, time: string): string => `Every ${n} days ${time}`,
      weekly: (time: string): string => `Weekly ${time}`,
      weeks: (n: number, time: string): string => `Every ${n} weeks ${time}`,
      invalid: "Invalid period",
    },
    legendEmpty: "No events yet",
    legendFilter: (name: string): string => `Show only ${name}'s events`,
    createAt: (label: string): string => `New event at ${label}`,
    loadFailed: (error: string): string => `Could not load the calendar: ${error}`,
    /** The "×" that puts the empty-calendar note away for good (the same sentence stays in the page's "?"). */
    dismissHint: "Got it",
    /** Under the start time: why two employees should not share one minute. */
    staggerHint:
      "Stagger the rota: give every employee its own minute; desks that fire together compete for the same budget and tickets.",
    /** Heads the advisory lines a calendar write answers with (the lines themselves come from the server, in English). */
    warningsPrefix: "Rota notice",
  },
  tickets: {
    title: "Tickets",
    info: "Five columns are a ticket's life: proposed → in progress → review → done / rejected. Drag a card to move it between columns, click a card's title to open its detail in place; a blocked ticket stays in its column with a badge. A ticket is the organization's unit of work: use New ticket, top right, to create one and name an owner, and the owner's desk session starts a ticket session for it.",
    columns: {
      proposed: "Proposed",
      in_progress: "In progress",
      review: "Review",
      done: "Done",
      rejected: "Rejected",
    } as Record<string, string>,
    blockedOnly: "Blocked only",
    create: "New ticket",
    createTitle: "New ticket",
    empty: "No tickets yet",
    emptyHint:
      "A ticket is the organization's unit of work: use New ticket, top right, to create one and name an owner, and the owner's desk session starts a ticket session for it.",
    /** The "×" that puts the empty-board note away for good (the same sentence stays in the page's "?"). */
    dismissHint: "Got it",
    columnEmpty: "Empty",
    ticketTitle: "Title",
    goal: "Goal",
    goalHint: "What to achieve, in a paragraph",
    acceptance: "Acceptance criteria",
    acceptanceHint: "What counts as done; checked one by one at review",
    result: "Result",
    owner: "Owner",
    noOwner: "Unassigned",
    ownerSelf: "Yourself",
    ownerSelfHint: "Left empty, the owner is you",
    parent: "Parent ticket",
    noParent: "None",
    notify: "Notify",
    notifyHint:
      "Comma-separated principals, e.g. agent:ceo, user:alice; notified on status changes",
    priority: "Priority",
    due: "Due",
    noDue: "None",
    blocked: "Blocked",
    blockedReason: "Blocked reason",
    blockedBy: "Waiting on",
    blockedTooltip: (reason: string, by: string): string => `Blocked: ${reason} (waiting on ${by})`,
    unblock: "Unblock",
    unblockConfirm: (title: string): string => `Unblock "${title}"?`,
    block: "Mark blocked",
    blockTitle: "Mark blocked",
    blockReasonHint: "One line on what it is stuck on",
    blockByHint: "The ticket or principal it waits on",
    sessions: "Ticket sessions",
    sessionsCount: (n: number): string => `${n} session${n === 1 ? "" : "s"}`,
    openSession: "Open session",
    openTicket: "Open ticket",
    progress: "Progress",
    progressEmpty: "No progress recorded yet",
    addProgress: "Add progress",
    progressPlaceholder: "One line on what moved…",
    children: "Child tickets",
    childrenEmpty: "No child tickets",
    cost: "This ticket's cost",
    rolledUpCost: "Total cost",
    parentLine: (title: string): string => `Parent ticket: ${title}`,
    moveTitle: "Move ticket",
    moveConfirm: (title: string, column: string): string => `Move "${title}" to "${column}"?`,
    rejectReason: "Rejection reason",
    rejectReasonHint: "One line on why, recorded under the ticket's result",
    moved: "Ticket moved",
    invalid:
      "This ticket is invalid: its status disagrees with its column, or its id is duplicated",
    invalidFiles: "Ticket files that failed to parse",
    edit: "Edit fields",
    saveConfirm: (title: string): string =>
      `Save the changes to "${title}"? This rewrites the ticket file.`,
    saved: "Ticket saved",
    created: "Ticket created",
    detail: "Ticket detail",
    back: "Back",
    dragHint: "Drag to another column to move it",
    searchPlaceholder: "Search title or id",
    searchNoMatch: "No matching tickets",
    dropHere: "Drop here",
    overdue: "Overdue",
    summary: "Details",
    history: "History",
    historyEmpty: "No history yet",
    historyActions: {
      created: "created",
      assigned: "assigned to",
      moved: "moved to",
      blocked: "blocked",
      unblocked: "unblocked",
      progress: "noted progress",
      session_started: "started a session",
      session_attached: "attached a session",
      edited: "edited",
    } as Record<string, string>,
    slug: "Id slug",
    slugHint:
      "Lowercase English words joined by hyphens, e.g. marketplace-site; no digits, derived from the title when left empty",
    slugInvalid: "Lowercase English words joined by hyphens only, no digits",
    noGoal: "No goal yet",
    noAcceptance: "No acceptance criteria yet",
    noResult: "No result yet",
    moveTo: "Move to…",
    move: "Move",
    copyId: "Copy ticket id",
    invalidTickets: "Invalid tickets",
    loadFailed: (error: string): string => `Could not load the board: ${error}`,
  },
  finance: {
    title: "Finance",
    info: "Budgets are set per employee and count the employee plus every subordinate; a period is a calendar month in the organization's timezone. Reaching 80% warns, reaching 100% pauses that employee's automatic triggers.",
    period: "Period",
    thisPeriod: "This period",
    prevPeriod: "Previous period",
    total: "Total",
    unpriced: "* Some usage ran on a model without pricing; the cost is a lower bound",
    budget: "Budget",
    editBudget: "Edit budget",
    budgetPlaceholder: "Unbounded",
    clearBudget: "Clear",
    budgetSaved: "Budget updated",
    own: "Own spend",
    cumulative: "Cumulative",
    /** The spend tree reads cumulative against budget in one column; own spend rides in the row tooltip. */
    cumulativeBudget: "Cumulative spend / budget",
    ratio: "Ratio",
    warned: "Warned",
    paused: "Paused",
    spendTree: "Spend tree",
    spendTreeInfo:
      "Expanded along the reporting line: cumulative spend includes every subordinate, and budget and ratio use the same measure.",
    ticketsTable: "Ticket spend",
    ticketsInfo:
      "Each ticket's contributing-session cost; the total cost adds up along parent tickets. A session attached to several tickets is shared between them.",
    ticketsEmpty: "No ticket spend this period",
    rolledUp: "Total cost",
    /** The ledger's fold: child tickets are hidden until the parent's chevron opens them. */
    expandChildren: "Show child tickets",
    collapseChildren: "Hide child tickets",
    childCount: (n: number): string => `${n} child ticket${n === 1 ? "" : "s"}`,
    trend: "Trend",
    alerts: "Alerts and pauses",
    alertsEmpty: "No alerts this period",
    alertWarned: (name: string, at: string): string => `${name} reached 80% of its budget at ${at}`,
    alertPaused: (name: string, at: string): string =>
      `${name} reached its budget at ${at}; automatic triggers paused`,
    alertsHint:
      "To lift a pause, raise the employee's budget or clear it; the next check resumes it automatically.",
    /** The KPI row under the title. */
    kpiTotal: "Total spend",
    orgBudget: "Organization budget (CEO)",
    kpiEmployees: "Employees",
    budgetsSet: (n: number): string => `${n} with a budget`,
    thresholds: "80% warns, 100% pauses",
    kpiAlerts: "Alerts",
    alertsSummary: (warned: number, paused: number): string =>
      `${warned} warned · ${paused} paused`,
    /** Column header explanations, and the tree's root mark. */
    cumulativeInfo:
      "The employee's own spend plus every subordinate's; budget and ratio use this measure.",
    rolledUpInfo: "This ticket plus its children.",
    root: "Root",
    /** The inline budget editor. */
    budgetEmptyHint: "Leave empty for unbounded",
    saveBudget: "Save budget",
    cancelEdit: "Cancel",
    editBudgetOf: (name: string): string => `Edit the budget of ${name}`,
    /** The ticket table's owner column and row action. */
    openTicket: "Open ticket",
    /** The trend section. */
    trendInfo:
      "The daily cost of every session in the organization, by the organization's timezone; only days with spend are drawn.",
    trendEmpty: "No spend recorded this period yet",
    /** The alert list. */
    alertsInfo:
      "Every check compares cumulative spend with the budget: reaching 80% records a warning, reaching 100% pauses the employee's and its subordinates' automatic triggers; lifting the pause resumes them.",
    pausedGroup: "Automatic triggers paused",
    warnedGroup: "Warned",
    warnedAt: (at: string): string => `reached 80% at ${at}`,
    pausedAt: (at: string): string => `reached 100% at ${at}`,
    /** A refetch failed while the last good data is still on screen. */
    refreshFailed: "Refresh failed; showing the last loaded data",
  },
  channels: {
    listTitle: "Channels",
    drawerLabel: "Channel list",
    allHands: "All hands",
    mine: "My channels",
    others: "Other channels",
    archivedGroup: "Archived",
    newChannel: "New channel",
    noChannels: "No channels yet",
    loadFailed: "Could not load the channels",
    join: "Join",
    joining: "Joining…",
    joined: "Joined the channel",
    joinTitle: "Join channel",
    joinConfirm:
      "Once you join, messages in this channel that @ you reach you, and you can post here.",
    mentionChip: "@me",
    badgeUnread: (n: number): string => `${n} unread`,
    badgeMentions: (n: number): string => `${n} mentioning me`,
    streamLabel: (name: string): string => `Messages in ${name}`,
    purpose: "Purpose",
    purposeEmpty: "No purpose written yet",
    memberCount: (n: number): string => `${n} member${n === 1 ? "" : "s"}`,
    memberList: "Channel members",
    invite: "Invite",
    inviteTitle: "Invite to the channel",
    inviteSearch: "Search employees and members",
    inviteEmpty: "Nobody left to invite",
    invited: (name: string): string => `Invited ${name}`,
    leave: "Leave",
    leaveTitle: "Leave the channel",
    leaveConfirm: (name: string): string =>
      `Leave "${name}"? You can still read it, but no @ will reach you and you cannot post until you join again.`,
    left: "Left the channel",
    channelMenu: "Channel actions",
    rename: "Rename",
    renameTitle: "Rename the channel",
    editPurpose: "Edit purpose",
    purposeTitle: "Edit the channel's purpose",
    archive: "Archive",
    unarchive: "Unarchive",
    archiveTitle: "Archive the channel",
    archiveConfirm: (name: string): string =>
      `Archive "${name}"? It becomes read-only and folds away under Archived; you can unarchive it at any time.`,
    archived: "Channel archived",
    unarchived: "Channel unarchived",
    archivedNotice: "This channel is archived and read-only. Unarchive it to post again.",
    notMemberNotice: "You are not in this channel yet. Join it to post.",
    channelLoadFailed: "Could not load the channel",
    allHandsInfo:
      "The all-hands channel is created with the organization: everyone in the organization is here — every employee, every Project member, and you, reading along — nobody can leave it and it cannot be archived. System notices — budget alerts and the like — are posted here.",
    channelInfo:
      "An invitation-only channel: an employee joins only when a member invites it, and an @ delivers within the channel's membership. People may join any channel themselves, and can read every channel.",
    allHandsNoArchive: "The all-hands channel cannot be archived",
    createTitle: "New channel",
    creating: "Creating…",
    created: "Channel created",
    idField: "Channel id",
    idHint: "2–64 characters: a lowercase letter, then lowercase letters, digits or underscores",
    idReserved: "default_channel belongs to the all-hands channel",
    idTaken: "That id is already taken",
    nameField: "Display name",
    nameHint: "Defaults to the id",
    purposeHint: "One line on what this channel is for",
    empty: "No messages yet",
    emptyHint:
      "Only an @ reaches an employee: @employee delivers to its desk session, @all to every member of the channel; a message without one is just a note.",
    placeholder: "Type a message — Enter sends, Shift+Enter breaks the line, @ mentions a member",
    send: "Send",
    you: "You",
    mentionAll: "Everyone",
    mentionAllDesc: "Every member of the channel",
    employees: "Employees",
    members: "Members",
    earlierDays: "Earlier days",
    ticketRef: (id: string): string => `Ticket ${id}`,
    sessionRef: "View session",
    replyTo: "Reply to",
    /** The ref chips' tooltips: what the chip's own text does not say — where it lands. */
    openTicketRef: "Open the ticket",
    replyToJump: "Jump to the message this replies to",
    hop: (n: number): string => `Relay · hop ${n}`,
    hopInfo:
      "Sent automatically by an employee's work run, N relays down an @-chain: a message from a person or the calendar is hop 0, an employee's reply from the run it triggered is hop 1 (unmarked), the reply of the next employee it @-mentioned is hop 2 … At the organization's chain limit (3 by default) an @ is recorded but triggers nobody, so two employees cannot @ each other all night.",
    hopSummary:
      'A mentioned employee may @ somebody else in its reply, which is an @-chain: from hop 2 a message is marked "Relay · hop N", and at the organization\'s chain limit (3 by default) an @ is recorded but triggers nobody.',
    today: "Today",
    yesterday: "Yesterday",
    noEarlier: "No earlier messages",
    unreadDivider: "Unread",
    newMessages: (n: number): string => `${n} new message${n === 1 ? "" : "s"}`,
    mentionPanel: "Mention",
    mentionsYou: "Mentions you",
    systemMessage: "System message",
    sentAt: (time: string): string => `Sent at ${time}`,
    notices: {
      employee_joined: (agent: string, title: string, manager: string): string =>
        `${agent} joined as ${title}, reporting to ${manager}.`,
      employee_left: (agent: string, manager: string): string =>
        `${agent} left the organization; reports now go to ${manager}.`,
      channel_created: (by: string): string => `${by} created the channel.`,
      channel_archived: (by: string): string => `${by} archived the channel.`,
      channel_unarchived: (by: string): string => `${by} unarchived the channel.`,
      channel_joined: (principal: string): string => `${principal} joined the channel.`,
      channel_invited: (by: string, principal: string): string =>
        `${by} invited ${principal} to the channel.`,
      channel_left: (principal: string): string => `${principal} left the channel.`,
      channel_removed: (by: string, principal: string): string =>
        `${by} removed ${principal} from the channel.`,
      budget_warned: (
        agent: string,
        percent: string,
        period: string,
        cost: string,
        budget: string,
      ): string =>
        `Budget warning: ${agent} has used ${percent}% of its ${period} budget (${cost} / ${budget} USD).`,
      budget_paused: (
        agent: string,
        percent: string,
        period: string,
        cost: string,
        budget: string,
      ): string =>
        `Budget pause: ${agent} reached ${percent}% of its ${period} budget (${cost} / ${budget} USD). Its calendar and its subordinates' are paused until the next month or a raised budget; mentions and direct conversations still work.`,
      ticket_blocked: (ticket: string, title: string): string =>
        `Ticket ${ticket} (${title}) is blocked.`,
      ticket_done: (ticket: string, title: string): string =>
        `Ticket ${ticket} (${title}) is done.`,
      ticket_rejected: (ticket: string, title: string): string =>
        `Ticket ${ticket} (${title}) was rejected.`,
    },
  },
  /** The handbook page: the knowledge base directory, its index and its documents. */
  handbook: {
    info: "The company's knowledge base: the Markdown documents under handbook/. The index (README.md) is the page every trigger makes the employee Agent read first; the other documents are listed from it and read on demand.",
    /** The pinned first row: the index, and why it is pinned. */
    indexLabel: "Index · read first every run",
    documents: "Documents",
    /** The tree's own controls: closing every folder, and what a folder row's count means. */
    collapseAll: "Collapse all",
    documentsInFolder: (n: number): string => `${n} document${n === 1 ? "" : "s"}`,
    noOtherDocuments: "No other documents yet. Create one and list it in the index.",
    emptyDocument: "This document is still empty.",
    newDocument: "New document",
    creating: "Creating…",
    pathField: "Path",
    pathPlaceholder: "decisions/2026-09-02-hire-plan.md",
    pathHint:
      "Relative to handbook/, folders separated by /; each segment starts with a letter or digit and uses only letters, digits, . _ -; .md is added when the extension is left out.",
    pathInvalid:
      "Invalid path: each segment starts with a letter or digit and uses only letters, digits, . _ -, folders separated by /, at most eight levels.",
    pathExists: "That document already exists.",
    documentCreated: "Document created",
    deleteDocument: "Delete document",
    deleteConfirm: (path: string): string =>
      `Delete ${path}? The document is removed from handbook/; the index entry pointing at it is not updated automatically.`,
    documentDeleted: "Document deleted",
    loadFailed: "Could not load the handbook",
    documentLoadFailed: "Could not load the document",
    /** A row's tooltip: when the file was last written, and its size. */
    updatedAt: (time: string, size: string): string => `Updated ${time} · ${size}`,
    /** Beside the editor's buttons: what the text is, and the shortcut. */
    editorHint: "Markdown · Ctrl/⌘+S to save",
  },
  /** The proposals page (the company-proposals plugin): the queue, one proposal's detail, its comments and the actions on it. */
  proposals: {
    title: "Proposals",
    info: "A proposal describes one change — the interfaces it touches, how, why, and one test case — written by an employee and built at the same time, its PR among the materials. Select a passage of the body to comment on it, then send the comments to the author in one batch with Request changes; approving requests the merge. Link one as proposal:<number>.",
    newProposal: "New proposal",
    newTitle: "New proposal",
    author: "Author",
    authorHint: "The employee that writes it; your brief goes straight to its desk",
    brief: "Brief",
    briefHint: "What to change and why, in a sentence or two",
    titleField: "Title",
    titleHint: "The author names it when writing",
    created: (n: number): string => `Proposal #${n} created`,
    queue: "Queue",
    search: "Search proposals",
    searchPlaceholder: "Search: is:open author:… text",
    /** The filter chips under the search box: lifecycle states, all, and the unread toggle. */
    chip: {
      group: "Filter by state",
      open: "Open",
      ready: "Ready",
      approved: "Approved",
      merged: "Merged",
      rejected: "Rejected",
      all: "All",
      unread: "Unread",
    },
    noMatch: (q: string): string => `No proposal matches "${q}"`,
    showAll: "Show all",
    queueEmpty: "No proposals yet",
    queueEmptyHint:
      "Click New proposal at the top right to delegate a change to an employee: it writes the proposal while another employee builds it.",
    dismissHint: "Got it",
    notFound: "Proposal does not exist",
    pickOne: "Pick a proposal from the queue",
    backToQueue: "Back to proposals",
    updated: "Updated",
    loadFailed: "Failed to load the proposal",
    unreadBadge: (n: number): string => `${n} unread`,
    unreadNote: (n: number): string => `${n} unread events`,
    status: {
      drafting: "Drafting",
      ready: "Ready",
      approved: "Approved",
      merged: "Merged",
      rejected: "Rejected",
    } as Record<string, string>,
    revision: (n: number): string => `Revision ${n}`,
    /** The panel above the body while an older approval stands: what changed since it. */
    diff: {
      title: (approved: number, head: number): string =>
        `Revised since approved r${approved} → r${head}`,
      approvedBy: (who: string, when: string): string => `Approved by ${who} ${when}`,
      hint: "An approval covers one revision; the author has published since, so it needs approving again.",
      view: { label: "View", changes: "Changes", latest: "Latest" },
      sectionAdded: "added",
      sectionRemoved: "removed",
      addedLabel: "Added",
      removedLabel: "Removed",
      changedLabel: "Changed",
      loadFailed: "Could not read the approved revision",
    },
    noRevision: "Not published yet",
    implementer: "Implementer",
    noImplementer: "Not yet named",
    delegatedBy: "Delegated by",
    briefSection: "Brief",
    materials: "Materials",
    materialsEmpty: "No materials yet — the implementer's PR lands here.",
    materialKind: {
      pr: "PR",
      issue: "Issue",
      branch: "Branch",
      doc: "Document",
      ticket: "Ticket",
      url: "Link",
    } as Record<string, string>,
    /** A `pr` material's state on GitHub. */
    materialStatus: {
      draft: "Draft",
      open: "Open",
      merged: "Merged",
      closed: "Closed",
    } as Record<string, string>,
    scope: "Scope",
    scopeEmpty: "The author has not listed the files yet.",
    scopeFile: "File",
    openFile: "Open beside the proposal",
    filePanel: {
      label: "File",
      close: "Close the file",
      copyPath: "Copy path",
      resize: "Resize the file panel",
      loadFailed: "Could not read this file",
      binary: "A binary file; not shown here",
      truncated: "Only the first 512 KB is shown",
      matches: (n: number) => `${n} matching ${n === 1 ? "line" : "lines"}`,
      noMatch: "No line matches the name pattern",
    },
    scopePattern: "Name pattern",
    scopeRoot: "Root",
    scopeWorkspace: "the shared workspace",
    scopeKind: { edit: "edit", new: "new", delete: "delete", rename: "rename" },
    scopeState: {
      exists: "exists",
      new: "not created yet",
      missing: "missing",
      deleted: "deleted",
      renamed: "rename pending",
    },
    scopeMissingHint: (where: string): string => `Not found under ${where}`,
    tests: "Tests",
    testsEmpty: "The author has not listed the tests yet.",
    testKind: { existing: "existing", new: "new", delete: "delete" },
    testMissing: "file missing",
    testMissingHint: (where: string): string =>
      `Listed as existing, but the file is not under ${where}`,
    testsShowMore: (n: number): string => `Show ${n} more`,
    testsShowLess: "Show less",
    testGroupToggle: (group: string): string => `Collapse or expand the ${group} group`,
    testGroupsUndeclared: "Undeclared groups",
    testGroupsUndeclaredNote:
      "These groups are no longer declared under Settings → Plugins → Company proposals; the next publish must move their tests into a declared group.",
    sections: "Body",
    sectionsEmpty: "The author has not published a body yet.",
    events: "Events",
    sessions: "Implementation sessions",
    openSession: "Open the session",
    discussions: "Discussions",
    discuss: "Discuss",
    discussHint: (who: string): string =>
      `Open a session with ${who} to talk this proposal over; its conclusion reaches ${who}'s desk once`,
    discussOpened: "Discussion opened",
    discussionOpen: "Open",
    discussionConcluded: "Conclusion sent",
    comment: "Comment",
    comments: (n: number): string => `${n} comments`,
    commentPlaceholder: "Say something about this passage…",
    commentSelection: "Comment on selection",
    commentParagraph: "Comment on this paragraph",
    selectionHint: "Select a passage of the body to comment on it",
    selectedText: "Selected text",
    selectionNotPlaced: "The selection could not be placed in the text; select again.",
    sectionComments: (n: number): string => `${n} comment${n === 1 ? "" : "s"} on this section`,
    staleComments: "Comments on earlier revisions",
    commentedOn: (quote: string): string => `“${quote}”`,
    addComment: "Add comment",
    commentEdited: "Comment updated",
    commentDeleted: "Comment withdrawn",
    commentAdded: "Comment noted — Request changes sends it to the author",
    pending: "Pending",
    resolved: "Resolved",
    resolvedNote: (text: string): string => `Resolved: ${text}`,
    fromRevision: (n: number): string => `A passage of revision ${n}`,
    showResolved: (n: number): string => `${n} resolved`,
    requestChanges: (n: number): string => (n > 0 ? `Request changes (${n})` : "Request changes"),
    requestChangesTitle: "Request changes",
    requestChangesConfirm: (n: number): string =>
      `Send ${n} pending comments to the author as one batch? The author works through them and publishes a new revision.`,
    changesRequested: "Sent to the author",
    approve: "Approve and request merge",
    approveTitle: "Approve the proposal",
    approveConfirm: (title: string): string =>
      `Approve "${title}" and request the merge? The implementer merges it into the main branch.`,
    approved: "Approved; the implementer is asked to merge",
    reject: "Reject",
    rejectTitle: "Reject the proposal",
    rejectConfirm: (title: string): string => `Reject "${title}"?`,
    rejectReason: "Reason",
    rejectReasonHint: "One line, recorded as an event the author sees",
    rejected: "Rejected",
    markMerged: "Mark merged",
    markMergedTitle: "Mark merged",
    markMergedConfirm: (title: string): string => `Mark "${title}" as merged?`,
    merged: "Marked as merged",
    /** One line per event on the timeline, by kind. */
    event: {
      notify_failed: "a notification did not go out",
      created: "created the proposal",
      revised: (n: number): string => `published revision ${n}`,
      ready: "marked it ready",
      changes_requested: (n: number): string => `requested changes (${n} comments)`,
      implementation_started: (who: string): string => `asked ${who} to implement it`,
      material_added: (label: string): string => `added material ${label}`,
      feedback: "sent implementation feedback",
      runtime_feedback: "sent runtime feedback",
      resolved: "resolved a comment",
      approved: "approved it and requested the merge",
      merged: "reported it merged",
      rejected: "rejected the proposal",
      brief_edited: "rewrote the brief",
      discussion_started: (who: string): string => `opened a discussion with ${who}`,
      discussion_concluded: "sent the discussion's conclusion to the owner's desk",
    },
    /** The capsule a `proposal:<n>` reference renders as: number, title, and the unread count when there is one. */
    capsule: (n: number, title: string): string => `#${n} ${title}`,
    capsuleUnread: (n: number): string => `${n} unread`,
    openProposal: "Open the proposal",
  },
};
