/**
 * The renderer registry, generated from src/module.json's `renderers` section — the one table
 * that names every renderer this build carries: the page renderers (`web.pages` entries and
 * server contributions name them by `builtin`), the session surface renderers, and the
 * company-mode nav rows a contributed page gets.
 *
 * Two files come out of it, because JSON can hold names but not imports:
 * - src/lib/renderers.gen.ts — data only (names, nav rows, their types); imports nothing, so any
 *   module may read it without joining an import cycle;
 * - src/renderers.gen.ts — the components, each imported through its Web module's entry; only
 *   the router reads it.
 *
 * Run `node scripts/gen-renderers.ts` after editing the manifest; test/renderers.test.ts fails
 * while either file is stale. A manifest that names a renderer it does not declare, or a module
 * that does not exist, is refused here rather than routed to /chat at run time.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";

interface RendererDecl {
  name: string;
  /** The Web module (src/features/<module>/) whose entry exports it. */
  module: string;
  /** The entry's export, when it is not `name`. */
  export?: string;
}

interface OrgNavDecl {
  /** A builtin renderer's name (`kind: "builtin"`), or the contributed page's key (`kind: "iframe"`). */
  key: string;
  kind: "builtin" | "iframe";
  label: string;
  segment: string;
}

export interface WebManifest {
  contributes: { "web.pages": Array<{ key: string; renderer: { builtin?: string } }> };
  renderers: { pages: RendererDecl[]; surfaces: RendererDecl[]; orgNav: OrgNavDecl[] };
}

export interface GeneratedRegistry {
  data: string;
  components: string;
}

const HEADER =
  "// Generated by scripts/gen-renderers.ts from src/module.json; do not edit.\n" +
  "// Regenerate with `node scripts/gen-renderers.ts` (test/renderers.test.ts checks it is current).\n";

function unique(what: string, names: readonly string[]): void {
  const seen = new Set<string>();
  for (const name of names) {
    if (seen.has(name)) throw new Error(`module.json: ${what} "${name}" is declared twice`);
    seen.add(name);
  }
}

/** Both files' text, or an error naming the first thing the manifest gets wrong. */
export function generateRegistry(
  manifest: WebManifest,
  moduleExists: (module: string) => boolean,
): GeneratedRegistry {
  const { pages, surfaces, orgNav } = manifest.renderers;
  unique(
    "page renderer",
    pages.map((r) => r.name),
  );
  unique(
    "surface renderer",
    surfaces.map((r) => r.name),
  );
  unique(
    "org nav row",
    orgNav.map((r) => r.key),
  );
  for (const r of [...pages, ...surfaces]) {
    if (!moduleExists(r.module))
      throw new Error(
        `module.json: renderer "${r.name}" names module "${r.module}", which has no entry`,
      );
  }
  const pageNames = new Set(pages.map((r) => r.name));
  for (const page of manifest.contributes["web.pages"]) {
    const builtin = page.renderer.builtin;
    if (builtin !== undefined && !pageNames.has(builtin))
      throw new Error(
        `module.json: page "${page.key}" names renderer "${builtin}", which is not declared`,
      );
  }
  for (const row of orgNav) {
    if (row.kind === "builtin" && !pageNames.has(row.key))
      throw new Error(
        `module.json: org nav row "${row.key}" names a page renderer that is not declared`,
      );
  }

  const list = (names: readonly string[]) => names.map((n) => `  ${JSON.stringify(n)},\n`).join("");
  const data =
    HEADER +
    "\n/** The page renderers this build carries: a page naming another `builtin` shows it is unavailable. */\n" +
    `export const PAGE_RENDERER_NAMES = [\n${list(pages.map((r) => r.name))}] as const;\n` +
    "export type PageRendererName = (typeof PAGE_RENDERER_NAMES)[number];\n" +
    "\n/** The session surface renderers this build carries. */\n" +
    `export const SURFACE_RENDERER_NAMES = [\n${list(surfaces.map((r) => r.name))}] as const;\n` +
    "export type SurfaceRendererName = (typeof SURFACE_RENDERER_NAMES)[number];\n" +
    "\n/** The company-mode nav rows of contributed pages, in row order (features/company/company-nav.ts). */\n" +
    "export const ORG_PAGE_RENDERERS = {\n" +
    orgNav
      .map(
        (row) =>
          `  ${JSON.stringify(row.key)}: {\n` +
          `    label: ${JSON.stringify(row.label)},\n` +
          `    segment: ${JSON.stringify(row.segment)},\n` +
          `    kind: ${JSON.stringify(row.kind)},\n` +
          "  },\n",
      )
      .join("") +
    "} as const;\n";

  const byModule = new Map<string, string[]>();
  for (const r of [...pages, ...surfaces]) {
    const binding = r.export === undefined ? r.name : `${r.export} as ${r.name}`;
    byModule.set(r.module, [...(byModule.get(r.module) ?? []), binding]);
  }
  const imports = [...byModule.keys()]
    .sort()
    .map(
      (module) => `import { ${byModule.get(module)!.join(", ")} } from "./features/${module}";\n`,
    )
    .join("");
  const entries = (decls: readonly RendererDecl[]) => decls.map((r) => `  ${r.name},\n`).join("");
  const components =
    HEADER +
    'import type { ComponentType } from "react";\n' +
    'import type { SurfaceRendererProps } from "./state/contributions";\n' +
    'import type { PageRendererName, SurfaceRendererName } from "./lib/renderers.gen";\n' +
    imports +
    "\n/** Each page renderer the manifest declares, by name. */\n" +
    "export const PAGE_RENDERERS: Record<PageRendererName, ComponentType> = {\n" +
    entries(pages) +
    "};\n" +
    "\n/** Each session surface renderer the manifest declares, by name. */\n" +
    "export const SURFACE_RENDERERS: Record<SurfaceRendererName, ComponentType<SurfaceRendererProps>> = {\n" +
    entries(surfaces) +
    "};\n";
  return { data, components };
}

const ROOT = fileURLToPath(new URL("..", import.meta.url));

export const OUTPUTS = {
  data: `${ROOT}src/lib/renderers.gen.ts`,
  components: `${ROOT}src/renderers.gen.ts`,
} as const;

/** The registry as it is written to disk: generated, then formatted by the repository's prettier. */
export async function generateFromDisk(): Promise<GeneratedRegistry> {
  const manifest = JSON.parse(readFileSync(`${ROOT}src/module.json`, "utf8")) as WebManifest;
  const out = generateRegistry(manifest, (module) =>
    existsSync(`${ROOT}src/features/${module}/index.ts`),
  );
  const pretty = async (text: string, filepath: string) =>
    format(text, { ...(await resolveConfig(filepath)), filepath });
  return {
    data: await pretty(out.data, OUTPUTS.data),
    components: await pretty(out.components, OUTPUTS.components),
  };
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1]) {
  const out = await generateFromDisk();
  writeFileSync(OUTPUTS.data, out.data);
  writeFileSync(OUTPUTS.components, out.components);
}
